@extends('admin.layouts.app')

@section('title', $config['label'])

@section('content')
    <section class="admin-resource-page system-settings-resource" data-auto-open="{{ $edit ? 'particle-modal' : '' }}">
        <div class="admin-resource-heading"><div><h1>{{ $config['label'] }} List</h1></div><a class="admin-button admin-button-primary" href="{{ route('admin.systemsettings.dashboard.short', absolute: false) }}">Dashboard</a></div>
        <div class="admin-particle-content">
            <div class="admin-resource-toolbar"><form method="get" action="{{ route('admin.systemsettings.resource', ['slug' => $slug], false) }}"><input name="search" value="{{ $search }}" placeholder="Search {{ strtolower($config['label']) }}..."><button class="admin-button admin-search-button" type="submit" aria-label="Search" title="Search"><i class="fa-solid fa-magnifying-glass"></i></button></form><button class="admin-button admin-button-primary" type="button" data-modal-open="particle-modal"><i class="fa-solid fa-plus"></i> Add {{ $config['label'] }}</button></div>
            <div id="particle-modal" class="admin-modal" hidden role="dialog" aria-modal="true" aria-labelledby="particle-modal-title"><div class="admin-modal-backdrop" data-modal-close></div><div class="admin-modal-dialog"><div class="admin-modal-header"><h2 id="particle-modal-title">{{ $edit ? 'Edit' : 'Add' }} {{ $config['label'] }}</h2><button type="button" class="admin-modal-close" data-modal-close aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><form class="admin-modal-form" method="post" action="{{ $edit ? route('admin.systemsettings.update', ['slug' => $slug, 'id' => $edit->id], false) : route('admin.systemsettings.store', ['slug' => $slug], false) }}">@csrf<div class="admin-modal-fields">@foreach($fields as $field)<label class="admin-field"><span>{{ str($field)->replace('_', ' ')->title() }} @if($field === 'name')<b>*</b>@endif</span>@if($field === 'is_active')<select name="{{ $field }}"><option value="1" @selected(($edit->{$field} ?? 1) == 1)>Active</option><option value="0" @selected(($edit->{$field} ?? 1) == 0)>Inactive</option></select>@elseif(in_array($field, ['note', 'description'], true))<textarea name="{{ $field }}">{{ $edit->{$field} ?? '' }}</textarea>@else<input name="{{ $field }}" value="{{ $edit->{$field} ?? '' }}" type="{{ str_contains($field, 'date') ? 'date' : 'text' }}">@endif</label>@endforeach</div><div class="admin-modal-footer"><button class="admin-button" type="button" data-modal-close>Cancel</button><button class="admin-button admin-button-primary" type="submit">{{ $edit ? 'Update' : 'Save' }}</button></div></form></div></div>
            <div class="admin-resource-table-wrap"><table class="admin-resource-table"><thead><tr>@foreach(array_values(array_filter($columns, fn($column) => !in_array($column, ['updated_at', 'created_at'], true))) as $column)<th>{{ str($column)->replace('_', ' ')->title() }}</th>@endforeach<th>Actions</th></tr></thead><tbody>@forelse($records as $record)<tr>@foreach(array_values(array_filter($columns, fn($column) => !in_array($column, ['updated_at', 'created_at'], true))) as $column)<td>{{ is_scalar($record->{$column} ?? null) ? $record->{$column} : '' }}</td>@endforeach<td class="admin-resource-actions"><a class="admin-icon-button" href="{{ route('admin.systemsettings.resource', ['slug' => $slug, 'edit' => $record->id], false) }}" aria-label="Edit"><i class="fa-solid fa-pen"></i></a><form method="post" action="{{ route('admin.systemsettings.destroy', ['slug' => $slug, 'id' => $record->id], false) }}">@csrf<button class="admin-icon-button is-danger" type="submit" aria-label="Delete"><i class="fa-solid fa-trash"></i></button></form></td></tr>@empty<tr><td colspan="99">No records found.</td></tr>@endforelse</tbody></table></div><div class="admin-pagination">{{ $records->links() }}</div>
        </div>
    </section>
@endsection
