@extends('admin.layouts.app')
@section('title','Training Agenda')
@push('styles')<style>.tools{display:none!important}</style>@endpush
@push('styles')<style>.actions a,.actions button{font-size:0}.actions a:first-child:before{content:'\f06e';font-family:FontAwesome;font-size:12px}.actions a:nth-child(2):before{content:'\f040';font-family:FontAwesome;font-size:12px}.actions button:before{content:'\f00d';font-family:FontAwesome;font-size:12px}</style>@endpush
@push('styles')<style>.actions a,.actions button{border:1px solid #555!important;border-radius:5px!important;background:#666!important;color:#fff!important;transition:.15s}.actions a:nth-child(2){background:#fff!important;color:#555!important}.actions button{background:#e53935!important;border-color:#c62828!important}.actions a:hover,.actions a:focus,.actions button:hover,.actions button:focus{outline:2px solid #333;outline-offset:1px}</style>@endpush
@push('styles')<style>#agenda-table th{white-space:nowrap;font-size:11px}</style>@endpush
@push('styles')<style>#agenda-table th:nth-child(1),#agenda-table td:nth-child(1){width:6%}#agenda-table th:nth-child(2),#agenda-table td:nth-child(2){width:15%}#agenda-table th:nth-child(3),#agenda-table td:nth-child(3){width:18%}#agenda-table th:nth-child(4),#agenda-table td:nth-child(4){width:18%}#agenda-table th:nth-child(5),#agenda-table td:nth-child(5){width:18%}#agenda-table th:nth-child(6),#agenda-table td:nth-child(6){width:13%}#agenda-table th:nth-child(7),#agenda-table td:nth-child(7){width:12%}</style>@endpush
@push('styles')<style>#agenda-table td{font-size:12px}</style>@endpush
@push('styles')<style>#agenda-table th:nth-child(5),#agenda-table td:nth-child(5){width:15%}#agenda-table th:nth-child(7),#agenda-table td:nth-child(7){width:15%}#agenda-table .actions a,#agenda-table .actions button{box-sizing:border-box;width:22px;height:22px;margin-right:1px}</style>@endpush
@php $editing=$agenda&&!$viewMode; $items=$agenda?->agenda_items ?: [['topic'=>'','resource_person'=>'','venue'=>'','timing_date'=>'','timing_time'=>'','audience'=>'','required_material'=>'']]; @endphp
@section('content')
<div class="training-layout"><section class="training-form"><h2>{{ $viewMode?'View Training Agenda':($editing?'Edit Training Agenda':'Add Training Agenda') }}</h2><form method="POST" action="{{ $editing?route('admin.hrms.training.agenda.update',$agenda,false):route('admin.hrms.training.agenda.store',absolute:false) }}">@csrf @if($editing) @method('PUT') @endif @if(session('success'))<div class="success">{{session('success')}}</div>@endif @if($errors->any())<div class="error">Please correct the highlighted fields.</div>@endif
<label>Prepared By <b>*</b></label>@if($viewMode)<input value="{{$agenda->prepared_by}}" readonly>@else<select name="prepared_by" required><option value="">Select Staff</option>@foreach($staff as $person)<option value="{{trim($person->name.' '.$person->surname)}}" @selected($agenda?->prepared_by===trim($person->name.' '.$person->surname))>{{trim($person->name.' '.$person->surname)}}</option>@endforeach</select>@endif
<label>Agenda Items</label><div id="agenda-items">@foreach($items as $i=>$item)<div class="agenda-item"><div class="two"><input name="topic[]" placeholder="Topic" value="{{$item['topic']??''}}" {{ $viewMode?'readonly':'' }}><input name="resource_person[]" placeholder="Resource Person" value="{{$item['resource_person']??''}}" {{ $viewMode?'readonly':'' }}></div><div class="three"><input name="venue[]" placeholder="Venue" value="{{$item['venue']??''}}" {{ $viewMode?'readonly':'' }}><input type="date" name="timing_date[]" value="{{$item['timing_date']??''}}" {{ $viewMode?'readonly':'' }}><input type="time" name="timing_time[]" value="{{$item['timing_time']??''}}" {{ $viewMode?'readonly':'' }}></div><div class="two"><input name="audience[]" placeholder="Audience" value="{{$item['audience']??''}}" {{ $viewMode?'readonly':'' }}><input name="required_material[]" placeholder="Required Material" value="{{$item['required_material']??''}}" {{ $viewMode?'readonly':'' }}></div>@if(!$viewMode)<button type="button" class="remove" onclick="this.parentElement.remove()">Remove</button>@endif</div>@endforeach</div>@if(!$viewMode)<button type="button" class="add" onclick="addAgendaItem()">Add Item</button>@endif
<div class="form-actions">@if($viewMode)<a href="{{route('admin.hrms.training.agenda.index',absolute:false)}}">Back</a><a class="primary" href="{{route('admin.hrms.training.agenda.edit',$agenda,false)}}">Edit</a>@else<a href="{{route('admin.hrms.training.agenda.index',absolute:false)}}">{{ $editing?'Cancel':'Reset' }}</a><button class="primary">{{ $editing?'Update':'Save' }}</button>@endif</div></form></section>
<section class="training-list"><h2>Training Agenda List</h2><div class="toolbar"><input id="agenda-search" placeholder="Search..."><div class="tools">▣ ▧ ▤ ▥ ▣</div></div><table id="agenda-table"><thead><tr><th>ID</th><th>Prepared By</th><th>Topics</th><th>Resource Persons</th><th>Dates & Times</th><th>Created Date</th><th>Action</th></tr></thead><tbody>@forelse($agendas as $row)@php $rows=$row->agenda_items?:[]; $topics=collect($rows)->pluck('topic')->filter()->implode(', ');$resources=collect($rows)->pluck('resource_person')->filter()->implode(', ');$dates=collect($rows)->map(fn($x)=>trim(($x['timing_date']??'').' '.($x['timing_time']??'')))->filter()->implode(', ');@endphp<tr><td>{{$row->id}}</td><td>{{$row->prepared_by}}</td><td>{{$topics}}</td><td>{{$resources}}</td><td>{{$dates}}</td><td>{{$row->created_at?->format('Y-m-d')}}</td><td class="actions"><a href="{{route('admin.hrms.training.agenda.show',$row,false)}}">◉</a><a href="{{route('admin.hrms.training.agenda.edit',$row,false)}}">✎</a><form method="POST" action="{{route('admin.hrms.training.agenda.destroy',$row,false)}}" onsubmit="return confirm('Delete this agenda?')">@csrf @method('DELETE')<button>×</button></form></td></tr>@empty<tr><td colspan="7" class="empty">No training agenda found</td></tr>@endforelse</tbody></table></section></div>
@endsection
@push('styles')<style>.training-layout{display:grid;grid-template-columns:minmax(360px,1fr) minmax(0,2fr);gap:12px;align-items:start}.training-form,.training-list{background:#fff;border:1px solid #d8dce5;box-shadow:0 1px 3px #0001}.training-form h2,.training-list h2{font-size:16px;font-weight:500;padding:12px 14px;border-bottom:1px solid #d8dce5;margin:0}.training-form form{padding:14px}.training-form label{display:block;font-size:13px;font-weight:600;margin:0 0 5px}.training-form label b{color:#dc3545}.training-form input,.training-form select{width:100%;height:35px;border:1px solid #cfd6e0;padding:6px 9px;margin-bottom:10px;font-size:12px}.agenda-item{border:1px solid #d8dce5;padding:10px;margin:5px 0 10px}.two,.three{display:grid;gap:8px}.two{grid-template-columns:1fr 1fr}.three{grid-template-columns:1fr 1fr 1fr}.agenda-item input{margin-bottom:6px}.add,.remove,.form-actions a,.form-actions button{border:0;padding:7px 12px;font-size:12px;color:#fff;text-decoration:none}.add{background:#198754}.remove{background:#dc3545}.form-actions{display:flex;justify-content:flex-end;gap:7px;border-top:1px solid #eee;margin:14px -14px -14px;padding:12px 14px}.form-actions a:not(.primary){border:1px solid #cfd6e0;color:#333}.primary{background:#264796!important;color:#fff!important}.training-list{padding-bottom:12px}.toolbar{display:flex;justify-content:space-between;padding:8px 12px;border-bottom:1px solid #d8dce5}.toolbar input{width:220px;height:32px;border:1px solid #aeb8c6;border-radius:6px;padding:5px;font-size:12px}.tools{background:#62676d;color:#fff;padding:7px 10px;word-spacing:6px;border-radius:5px}#agenda-table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:11px;margin:10px 12px;width:calc(100% - 24px)}#agenda-table th{background:#626262;color:#fff;border:1px solid #858585;padding:8px;text-align:left}#agenda-table td{border:1px solid #bfc8d4;padding:6px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#agenda-table th:nth-child(1){width:6%}#agenda-table th:nth-child(2){width:15%}#agenda-table th:nth-child(3){width:20%}#agenda-table th:nth-child(4){width:18%}#agenda-table th:nth-child(5){width:18%}#agenda-table th:nth-child(6){width:13%}#agenda-table th:nth-child(7){width:10%}.actions{white-space:nowrap!important;overflow:visible!important}.actions a,.actions button{display:inline-flex;width:22px;height:22px;align-items:center;justify-content:center;margin-right:2px;border:0;background:#264796;color:#fff;text-decoration:none}.actions a:first-child{background:#17a2b8}.actions button{background:#dc3545}.actions form{display:inline}.empty{text-align:center}@media(max-width:900px){.training-layout{grid-template-columns:1fr}.two,.three{grid-template-columns:1fr}.toolbar{flex-direction:column;gap:6px}.toolbar input{width:100%}}</style>@endpush
@push('scripts')<script>function addAgendaItem(){const x=document.createElement('div');x.className='agenda-item';x.innerHTML='<div class="two"><input name="topic[]" placeholder="Topic"><input name="resource_person[]" placeholder="Resource Person"></div><div class="three"><input name="venue[]" placeholder="Venue"><input type="date" name="timing_date[]"><input type="time" name="timing_time[]"></div><div class="two"><input name="audience[]" placeholder="Audience"><input name="required_material[]" placeholder="Required Material"></div><button type="button" class="remove" onclick="this.parentElement.remove()">Remove</button>';document.getElementById('agenda-items').appendChild(x)}document.addEventListener('DOMContentLoaded',()=>document.querySelector('.training-list input')?.addEventListener('input',e=>document.querySelectorAll('#agenda-table tbody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(e.target.value.toLowerCase())?'':'none')))</script>@endpush
