@extends('admin.layouts.app')
@section('title','Training Agenda')
@php $editing=$agenda&&!$viewMode; $items=$agenda?->agenda_items ?: [['topic'=>'','resource_person'=>'','venue'=>'','timing_date'=>'','timing_time'=>'','audience'=>'','required_material'=>'']]; @endphp
@section('content')
<div class="training-layout"><section class="training-form"><h2>{{ $viewMode?'View Training Agenda':($editing?'Edit Training Agenda':'Add Training Agenda') }}</h2><form method="POST" action="{{ $editing?route('admin.hrms.training.agenda.update',$agenda,false):route('admin.hrms.training.agenda.store',absolute:false) }}">@csrf @if($editing) @method('PUT') @endif @if(session('success'))<div class="success">{{session('success')}}</div>@endif @if($errors->any())<div class="error">Please correct the highlighted fields.</div>@endif
<label>Prepared By <b>*</b></label>@if($viewMode)<input value="{{$agenda->prepared_by}}" readonly>@else<select name="prepared_by" required><option value="">Select Staff</option>@foreach($staff as $person)<option value="{{trim($person->name.' '.$person->surname)}}" @selected($agenda?->prepared_by===trim($person->name.' '.$person->surname))>{{trim($person->name.' '.$person->surname)}}</option>@endforeach</select>@endif
<label>Agenda Items</label><div id="agenda-items">@foreach($items as $i=>$item)<div class="agenda-item"><div class="two"><input name="topic[]" placeholder="Topic" value="{{$item['topic']??''}}" {{ $viewMode?'readonly':'' }}><input name="resource_person[]" placeholder="Resource Person" value="{{$item['resource_person']??''}}" {{ $viewMode?'readonly':'' }}></div><div class="three"><input name="venue[]" placeholder="Venue" value="{{$item['venue']??''}}" {{ $viewMode?'readonly':'' }}><input type="date" name="timing_date[]" value="{{$item['timing_date']??''}}" {{ $viewMode?'readonly':'' }}><input type="time" name="timing_time[]" value="{{$item['timing_time']??''}}" {{ $viewMode?'readonly':'' }}></div><div class="two"><input name="audience[]" placeholder="Audience" value="{{$item['audience']??''}}" {{ $viewMode?'readonly':'' }}><input name="required_material[]" placeholder="Required Material" value="{{$item['required_material']??''}}" {{ $viewMode?'readonly':'' }}></div>@if(!$viewMode)<button type="button" class="remove" onclick="this.parentElement.remove()">Remove</button>@endif</div>@endforeach</div>@if(!$viewMode)<button type="button" class="add" onclick="addAgendaItem()">Add Item</button>@endif
<div class="form-actions">@if($viewMode)<a href="{{route('admin.hrms.training.agenda.index',absolute:false)}}">Back</a><a class="primary" href="{{route('admin.hrms.training.agenda.edit',$agenda,false)}}">Edit</a>@else<a href="{{route('admin.hrms.training.agenda.index',absolute:false)}}">{{ $editing?'Cancel':'Reset' }}</a><button class="primary">{{ $editing?'Update':'Save' }}</button>@endif</div></form></section>
<section class="training-list"><h2>Training Agenda List</h2><div class="toolbar"><input id="agenda-search" placeholder="Search..."><div class="tools">▣ ▧ ▤ ▥ ▣</div></div><table id="agenda-table"><thead><tr><th>ID</th><th>Prepared By</th><th>Topics</th><th>Resource Persons</th><th>Dates & Times</th><th>Created Date</th><th>Action</th></tr></thead><tbody>@forelse($agendas as $row)@php $rows=$row->agenda_items?:[]; $topics=collect($rows)->pluck('topic')->filter()->implode(', ');$resources=collect($rows)->pluck('resource_person')->filter()->implode(', ');$dates=collect($rows)->map(fn($x)=>trim(($x['timing_date']??'').' '.($x['timing_time']??'')))->filter()->implode(', ');@endphp<tr><td>{{$row->id}}</td><td>{{$row->prepared_by}}</td><td>{{$topics}}</td><td>{{$resources}}</td><td>{{$dates}}</td><td>{{$row->created_at?->format('Y-m-d')}}</td><td class="actions"><a href="{{route('admin.hrms.training.agenda.show',$row,false)}}">◉</a><a href="{{route('admin.hrms.training.agenda.edit',$row,false)}}">✎</a><form method="POST" action="{{route('admin.hrms.training.agenda.destroy',$row,false)}}" onsubmit="return confirm('Delete this agenda?')">@csrf @method('DELETE')<button>×</button></form></td></tr>@empty<tr><td colspan="7" class="empty">No training agenda found</td></tr>@endforelse</tbody></table></section></div>
@endsection
@push('scripts')<script>function addAgendaItem(){const x=document.createElement('div');x.className='agenda-item';x.innerHTML='<div class="two"><input name="topic[]" placeholder="Topic"><input name="resource_person[]" placeholder="Resource Person"></div><div class="three"><input name="venue[]" placeholder="Venue"><input type="date" name="timing_date[]"><input type="time" name="timing_time[]"></div><div class="two"><input name="audience[]" placeholder="Audience"><input name="required_material[]" placeholder="Required Material"></div><button type="button" class="remove" onclick="this.parentElement.remove()">Remove</button>';document.getElementById('agenda-items').appendChild(x)}document.addEventListener('DOMContentLoaded',()=>document.querySelector('.training-list input')?.addEventListener('input',e=>document.querySelectorAll('#agenda-table tbody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(e.target.value.toLowerCase())?'':'none')))</script>@endpush
