@extends('admin.layouts.app')
@section('title','Training Need Analysis')
@push('styles')<style>.tools{display:none!important}</style>@endpush
@push('styles')<style>.actions a,.actions button{font-size:0}.actions a:first-child:before{content:'\f06e';font-family:FontAwesome;font-size:12px}.actions a:nth-child(2):before{content:'\f040';font-family:FontAwesome;font-size:12px}.actions button:before{content:'\f00d';font-family:FontAwesome;font-size:12px}</style>@endpush
@push('styles')<style>.actions a,.actions button{border:1px solid #555!important;border-radius:5px!important;background:#666!important;color:#fff!important;transition:.15s}.actions a:nth-child(2){background:#fff!important;color:#555!important}.actions button{background:#e53935!important;border-color:#c62828!important}.actions a:hover,.actions a:focus,.actions button:hover,.actions button:focus{outline:2px solid #333;outline-offset:1px}</style>@endpush
@push('styles')<style>#analysis-table th{white-space:nowrap;font-size:11px}</style>@endpush
@push('styles')<style>#analysis-table th:nth-child(1),#analysis-table td:nth-child(1){width:6%}#analysis-table th:nth-child(2),#analysis-table td:nth-child(2){width:15%}#analysis-table th:nth-child(3),#analysis-table td:nth-child(3){width:15%}#analysis-table th:nth-child(4),#analysis-table td:nth-child(4){width:12%}#analysis-table th:nth-child(5),#analysis-table td:nth-child(5){width:12%}#analysis-table th:nth-child(6),#analysis-table td:nth-child(6){width:18%}#analysis-table th:nth-child(7),#analysis-table td:nth-child(7){width:12%}#analysis-table th:nth-child(8),#analysis-table td:nth-child(8){width:10%}</style>@endpush
@push('styles')<style>#analysis-table td{font-size:12px}</style>@endpush
@push('styles')<style>#analysis-table th:nth-child(6),#analysis-table td:nth-child(6){width:15%}#analysis-table th:nth-child(8),#analysis-table td:nth-child(8){width:13%}#analysis-table .actions a,#analysis-table .actions button{box-sizing:border-box;width:22px;height:22px;margin-right:1px}</style>@endpush
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const field=document.querySelector('input[name="tna_date"]');if(field?.value)field.value=field.value.slice(0,10)})</script>@endpush
@php $editing=$analysis&&!$viewMode;$v=fn($k,$d='')=>old($k,$analysis?->{$k}??$d);$fields=[['major_task','1. MAJOR TASK OF JOB/DEPARTMENT','textarea'],['target_competencies','2. TARGET COMPETENCIES/AREAS OF TRAINING','textarea'],['required_arrangement','4. REQUIRED ARRANGEMENT AND ENVIRONMENT FOR TRAINING','textarea'],['school_benefits','5. EXPECTED BENEFITS TO SCHOOL','textarea'],['last_training_program','6. LAST TRAINING PROGRAM ATTENDED','textarea'],['suggest_training','7. SUGGEST TRAINING PROGRAMS','textarea'],['requester_sign','Requester Signature','text'],['hod_hrm_admin_sign','HOD/HRM/Admin Signature','text']];@endphp
@section('content')<div class="training-layout"><section class="training-form"><h2>{{ $viewMode?'View Training Need Analysis':($editing?'Edit Training Need Analysis':'Add Training Need Analysis') }}</h2><form method="POST" action="{{ $editing?route('admin.hrms.training.analysis.update',$analysis,false):route('admin.hrms.training.analysis.store',absolute:false) }}">@csrf @if($editing) @method('PUT') @endif @if(session('success'))<div class="success">{{session('success')}}</div>@endif @if($errors->any())<div class="error">Please correct the highlighted fields.</div>@endif
<label>Name <b>*</b></label>@if($viewMode)<input value="{{$v('name')}}" readonly>@else<select name="name" required><option value="">Select Staff</option>@foreach($staff as $person)<option @selected($v('name')===trim($person->name.' '.$person->surname))>{{trim($person->name.' '.$person->surname)}}</option>@endforeach</select>@endif<label>Designation <b>*</b></label><input name="designation" value="{{$v('designation')}}" {{ $viewMode?'readonly':'required' }}><label>Relevant POD</label><input name="relevant_pod" value="{{$v('relevant_pod')}}" {{ $viewMode?'readonly':'' }}><label>Campus</label><input name="campus" value="{{$v('campus')}}" {{ $viewMode?'readonly':'' }}><label>TNA Date <b>*</b></label><input type="date" name="tna_date" value="{{$v('tna_date',$today)}}" {{ $viewMode?'readonly':'required' }}>
@foreach($fields as [$name,$label,$type])<label>{{$label}}</label>@if($type==='textarea')<textarea name="{{$name}}" rows="3" {{ $viewMode?'readonly':'' }}>{{$v($name)}}</textarea>@else<input name="{{$name}}" value="{{$v($name)}}" {{ $viewMode?'readonly':'' }}>@endif @endforeach
<label>3. WHICH MODE OF TRAINING IS SUITABLE</label>@if($viewMode)<input value="{{$v('mode_of_training')}}" readonly>@else<select name="mode_of_training"><option value="">Select Mode</option>@foreach($modes as $mode)<option @selected($v('mode_of_training')===$mode)>{{$mode}}</option>@endforeach</select>@endif
<div class="form-actions">@if($viewMode)<a href="{{route('admin.hrms.training.analysis.index',absolute:false)}}">Back</a><a class="primary" href="{{route('admin.hrms.training.analysis.edit',$analysis,false)}}">Edit</a>@else<a href="{{route('admin.hrms.training.analysis.index',absolute:false)}}">{{ $editing?'Cancel':'Reset' }}</a><button class="primary">{{ $editing?'Update':'Save' }}</button>@endif</div></form></section>
<section class="training-list"><h2>Training Need Analysis List</h2><div class="toolbar"><input id="analysis-search" placeholder="Search..."><div class="tools">▣ ▧ ▤ ▥ ▣</div></div><table id="analysis-table"><thead><tr><th>ID</th><th>Name</th><th>Designation</th><th>Campus</th><th>TNA Date</th><th>Mode of Training</th><th>Created Date</th><th>Action</th></tr></thead><tbody>@forelse($analyses as $row)<tr><td>{{$row->id}}</td><td>{{$row->name}}</td><td>{{$row->designation}}</td><td>{{$row->campus}}</td><td>{{$row->tna_date?->format('Y-m-d')}}</td><td>{{$row->mode_of_training}}</td><td>{{$row->created_at?->format('Y-m-d')}}</td><td class="actions"><a href="{{route('admin.hrms.training.analysis.show',$row,false)}}">◉</a><a href="{{route('admin.hrms.training.analysis.edit',$row,false)}}">✎</a><form method="POST" action="{{route('admin.hrms.training.analysis.destroy',$row,false)}}" onsubmit="return confirm('Delete this analysis?')">@csrf @method('DELETE')<button>×</button></form></td></tr>@empty<tr><td colspan="8" class="empty">No training need analysis found</td></tr>@endforelse</tbody></table></section></div>@endsection
@push('styles')<style>.training-layout{display:grid;grid-template-columns:minmax(360px,1fr) minmax(0,2fr);gap:12px;align-items:start}.training-form,.training-list{background:#fff;border:1px solid #d8dce5;box-shadow:0 1px 3px #0001}.training-form h2,.training-list h2{font-size:16px;font-weight:500;padding:12px 14px;border-bottom:1px solid #d8dce5;margin:0}.training-form form{padding:14px}.training-form label{display:block;font-size:13px;font-weight:600;margin:0 0 5px}.training-form label b{color:#dc3545}.training-form input,.training-form select,.training-form textarea{width:100%;border:1px solid #cfd6e0;padding:7px 9px;margin-bottom:10px;font-size:12px}.form-actions{display:flex;justify-content:flex-end;gap:7px;border-top:1px solid #eee;margin:14px -14px -14px;padding:12px 14px}.form-actions a,.form-actions button{padding:7px 12px;text-decoration:none;border:1px solid #cfd6e0;color:#333;background:#fff}.form-actions .primary{background:#264796;color:#fff;border:0}.toolbar{display:flex;justify-content:space-between;padding:8px 12px;border-bottom:1px solid #d8dce5}.toolbar input{width:220px;height:32px;border:1px solid #aeb8c6;border-radius:6px;padding:5px;font-size:12px}.tools{background:#62676d;color:#fff;padding:7px 10px;word-spacing:6px;border-radius:5px}#analysis-table{width:calc(100% - 24px);margin:10px 12px;border-collapse:collapse;table-layout:fixed;font-size:11px}#analysis-table th{background:#626262;color:#fff;border:1px solid #858585;padding:8px;text-align:left}#analysis-table td{border:1px solid #bfc8d4;padding:6px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.actions{white-space:nowrap!important;overflow:visible!important}.actions a,.actions button{display:inline-flex;width:22px;height:22px;align-items:center;justify-content:center;margin-right:2px;border:0;background:#264796;color:#fff;text-decoration:none}.actions a:first-child{background:#17a2b8}.actions button{background:#dc3545}.actions form{display:inline}.empty{text-align:center}@media(max-width:900px){.training-layout{grid-template-columns:1fr}.toolbar{flex-direction:column;gap:6px}.toolbar input{width:100%}}</style>@endpush
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>document.getElementById('analysis-search')?.addEventListener('input',e=>document.querySelectorAll('#analysis-table tbody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(e.target.value.toLowerCase())?'':'none')))</script>@endpush
