@extends('admin.layouts.app')
@section('title','Training Need Analysis')
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const field=document.querySelector('input[name="tna_date"]');if(field?.value)field.value=field.value.slice(0,10)})</script>@endpush
@php $editing=$analysis&&!$viewMode;$v=fn($k,$d='')=>old($k,$analysis?->{$k}??$d);$fields=[['major_task','1. MAJOR TASK OF JOB/DEPARTMENT','textarea'],['target_competencies','2. TARGET COMPETENCIES/AREAS OF TRAINING','textarea'],['required_arrangement','4. REQUIRED ARRANGEMENT AND ENVIRONMENT FOR TRAINING','textarea'],['school_benefits','5. EXPECTED BENEFITS TO SCHOOL','textarea'],['last_training_program','6. LAST TRAINING PROGRAM ATTENDED','textarea'],['suggest_training','7. SUGGEST TRAINING PROGRAMS','textarea'],['requester_sign','Requester Signature','text'],['hod_hrm_admin_sign','HOD/HRM/Admin Signature','text']];@endphp
@section('content')<div class="training-layout"><section class="training-form"><h2>{{ $viewMode?'View Training Need Analysis':($editing?'Edit Training Need Analysis':'Add Training Need Analysis') }}</h2><form method="POST" action="{{ $editing?route('admin.hrms.training.analysis.update',$analysis,false):route('admin.hrms.training.analysis.store',absolute:false) }}">@csrf @if($editing) @method('PUT') @endif @if(session('success'))<div class="success">{{session('success')}}</div>@endif @if($errors->any())<div class="error">Please correct the highlighted fields.</div>@endif
<label>Name <b>*</b></label>@if($viewMode)<input value="{{$v('name')}}" readonly>@else<select name="name" required><option value="">Select Staff</option>@foreach($staff as $person)<option @selected($v('name')===trim($person->name.' '.$person->surname))>{{trim($person->name.' '.$person->surname)}}</option>@endforeach</select>@endif<label>Designation <b>*</b></label><input name="designation" value="{{$v('designation')}}" {{ $viewMode?'readonly':'required' }}><label>Relevant POD</label><input name="relevant_pod" value="{{$v('relevant_pod')}}" {{ $viewMode?'readonly':'' }}><label>Campus</label><input name="campus" value="{{$v('campus')}}" {{ $viewMode?'readonly':'' }}><label>TNA Date <b>*</b></label><input type="date" name="tna_date" value="{{$v('tna_date',$today)}}" {{ $viewMode?'readonly':'required' }}>
@foreach($fields as [$name,$label,$type])<label>{{$label}}</label>@if($type==='textarea')<textarea name="{{$name}}" rows="3" {{ $viewMode?'readonly':'' }}>{{$v($name)}}</textarea>@else<input name="{{$name}}" value="{{$v($name)}}" {{ $viewMode?'readonly':'' }}>@endif @endforeach
<label>3. WHICH MODE OF TRAINING IS SUITABLE</label>@if($viewMode)<input value="{{$v('mode_of_training')}}" readonly>@else<select name="mode_of_training"><option value="">Select Mode</option>@foreach($modes as $mode)<option @selected($v('mode_of_training')===$mode)>{{$mode}}</option>@endforeach</select>@endif
<div class="form-actions">@if($viewMode)<a href="{{route('admin.hrms.training.analysis.index',absolute:false)}}">Back</a><a class="primary" href="{{route('admin.hrms.training.analysis.edit',$analysis,false)}}">Edit</a>@else<a href="{{route('admin.hrms.training.analysis.index',absolute:false)}}">{{ $editing?'Cancel':'Reset' }}</a><button class="primary">{{ $editing?'Update':'Save' }}</button>@endif</div></form></section>
<section class="training-list"><h2>Training Need Analysis List</h2><div class="toolbar"><input id="analysis-search" placeholder="Search..."><div class="tools">▣ ▧ ▤ ▥ ▣</div></div><table id="analysis-table"><thead><tr><th>ID</th><th>Name</th><th>Designation</th><th>Campus</th><th>TNA Date</th><th>Mode of Training</th><th>Created Date</th><th>Action</th></tr></thead><tbody>@forelse($analyses as $row)<tr><td>{{$row->id}}</td><td>{{$row->name}}</td><td>{{$row->designation}}</td><td>{{$row->campus}}</td><td>{{$row->tna_date?->format('Y-m-d')}}</td><td>{{$row->mode_of_training}}</td><td>{{$row->created_at?->format('Y-m-d')}}</td><td class="actions"><a href="{{route('admin.hrms.training.analysis.show',$row,false)}}">◉</a><a href="{{route('admin.hrms.training.analysis.edit',$row,false)}}">✎</a><form method="POST" action="{{route('admin.hrms.training.analysis.destroy',$row,false)}}" onsubmit="return confirm('Delete this analysis?')">@csrf @method('DELETE')<button>×</button></form></td></tr>@empty<tr><td colspan="8" class="empty">No training need analysis found</td></tr>@endforelse</tbody></table></section></div>@endsection
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>document.getElementById('analysis-search')?.addEventListener('input',e=>document.querySelectorAll('#analysis-table tbody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(e.target.value.toLowerCase())?'':'none')))</script>@endpush
