@extends('admin.layouts.app')
@section('title',$config['title'])
@php $editing=$record&&!$viewMode;$payload=is_array($record?->payload)?$record->payload:[];$root=str_replace('.index','',$config['route']);$get=fn($n,$d='')=>old($n,$payload[$n]??($record->{$n}??$d));@endphp
@section('content')
<div class="pc-layout"><section class="pc-form"><h2>{{ $viewMode?'View ':($editing?'Edit ':'Add ') }}{{$config['title']}}</h2><form method="POST" action="{{$editing?route($root.'.update',[$type,$record->id],false):route($root.'.store',$type,false)}}">@csrf @if($editing)@method('PUT')@endif @if(session('success'))<div class="pc-success">{{session('success')}}</div>@endif
@foreach($config['fields'] as $field) @php $name=$field['name'];$current=$get($name); @endphp<div class="pc-field"><label>{{$field['label']}} @if($field['required']??false)<b>*</b>@endif</label>@switch($field['type'])
@case('staff')<select name="{{$name}}" @required($field['required']??false) @disabled($viewMode)><option value="">Select Staff</option>@foreach($staff as $person)@php $personName=trim($person->name.' '.$person->surname);@endphp<option value="{{$personName}}" @selected($current===$personName)>{{$personName}} @if($person->employee_id)({{$person->employee_id}})@endif</option>@endforeach</select>@break
@case('campus')<select name="{{$name}}" required @disabled($viewMode)><option value="">Select Campus</option>@foreach($campuses as $campus)<option value="{{$campus->id}}" @selected((string)$current===(string)$campus->id)>{{$campus->name}}</option>@endforeach</select>@break
@case('text') @case('date')<input type="{{$field['type']}}" name="{{$name}}" value="{{$current}}" @required($field['required']??false) @readonly($viewMode)>@break
@case('textarea')<textarea name="{{$name}}" rows="4" @readonly($viewMode)>{{$current}}</textarea>@break
@case('radio')<div class="pc-options">@foreach($field['options'] as $option)<label><input type="radio" name="{{$name}}" value="{{$option}}" @checked($current===$option) @disabled($viewMode)> {{$option}}</label>@endforeach</div>@break
@case('checks')<div class="pc-options">@foreach($field['options'] as $option)<label><input type="checkbox" name="{{$name}}[]" value="{{$option}}" @checked(in_array($option,(array)$current)) @disabled($viewMode)> {{$option}}</label>@endforeach</div>@break
@case('school_scores')<div class="score-table"><table><tr><th>Sr.</th><th>Domain / Area</th><th>Parameter</th><th colspan="5">Score 1-5</th></tr>@foreach(['Health Safety & Environment|School Front decorum','Health Safety & Environment|Security Measures','Health Safety & Environment|School Indoor Decorum/Material Organization','Admission & Withdrawal|Admission & Withdrawal Records & Reports','Internal & External Communication|Communication & Postage Records & Reports','Effective Management Meetings|Meetings Records & Reports','Events Management|Events Records & Reports','Customer Services Management|Inquiries and Complaints Records & Reports','Staff Recruitment Process|CVs Records','Staff Recruitment Process|Staff Official Records'] as $i=>$item)@php [$domain,$parameter]=explode('|',$item);$selected=$current[$i]??'';@endphp<tr><td>{{$i+1}}</td><td>{{$domain}}</td><td>{{$parameter}}</td>@for($s=1;$s<=5;$s++)<td><input type="radio" name="scores[{{$i}}]" value="{{$s}}" @checked((string)$selected===(string)$s) @disabled($viewMode)></td>@endfor</tr>@endforeach</table></div>@break
@case('annual_scores') @case('monthly_scores') @php $params=$field['type']==='annual_scores'?['Punctuality','Manners & Decorum','Neatness','Dressing','Good Appearance','Politeness in Talk','Obedience to Seniors','Classroom Management','Student Motivation','Teaching Quality']:['Punctuality','Manners','Neatness','Dressing','Appearance','Politeness','Obedience','Care','Cleanliness','Usage','Behavior','Team','Cooperation','Task','Results','Method'];$scores=$current['scores']??[];@endphp<div class="score-table"><table><tr><th>Parameter</th><th>Max</th><th>Score</th></tr>@foreach($params as $i=>$param)@php $max=$field['type']==='annual_scores'?50:($i%5===0?10:5);@endphp<tr><td>{{$param}}</td><td>{{$max}}</td><td><input type="number" name="{{$name}}[scores][{{$i}}]" value="{{$scores[$i]??''}}" min="0" max="{{$max}}" @readonly($viewMode)></td></tr>@endforeach</table></div>@break
@case('clearance_items')<div class="repeat-list">@foreach((array)$current as $i=>$item)<div><input name="clearance_items[{{$i}}][item]" placeholder="Item" value="{{$item['item']??''}}"><input name="clearance_items[{{$i}}][remarks]" placeholder="Remarks" value="{{$item['remarks']??''}}"><input type="date" name="clearance_items[{{$i}}][date]" value="{{$item['date']??''}}"></div>@endforeach<div><input name="clearance_items[0][item]" placeholder="Item"><input name="clearance_items[0][remarks]" placeholder="Remarks"><input type="date" name="clearance_items[0][date]"></div></div>@break
@case('amounts') @php $amounts=is_array($current)?$current:[];@endphp<div class="amount-grid">@foreach(['payable_amount','security_deposit','provident_bonus','deductible_amount','loan_availed','fine_penalty','applicable_taxes','assets_not_returned','fee_of_children','net_payable','net_receivable'] as $amount)<input name="amounts[{{$amount}}]" placeholder="{{ucwords(str_replace('_',' ',$amount))}}" value="{{$amounts[$amount]??''}}" @readonly($viewMode)>@endforeach</div>@break
@case('ratings') @php $statements=['Job was challenging','There were sufficient opportunities for advancement','Workload was manageable','Opportunities for training were available'];$ratings=$current['job_ratings']??[];@endphp<div class="score-table"><table><tr><th>Statement</th><th>Strongly Disagree</th><th>Disagree</th><th>Agree</th><th>Strongly Agree</th></tr>@foreach($statements as $i=>$statement)<tr><td>{{$statement}}</td>@for($s=1;$s<=4;$s++)<td><input type="radio" name="job_ratings[{{$i}}]" value="{{$s}}" @checked(($ratings[$i]??'')==$s) @disabled($viewMode)></td>@endfor</tr>@endforeach</table></div>@break
@case('repeat')<div class="repeat-list"><input name="{{$name}}[]" value="{{is_array($current)?($current[0]??''):$current}}" placeholder="Enter details" @readonly($viewMode)></div>@break
@endswitch</div>@endforeach
<div class="pc-form-actions">@if($viewMode)<a href="{{route($config['route'],absolute:false)}}">Back</a><a class="primary" href="{{route($root.'.edit',[$type,$record->id],false)}}">Edit</a>@else<a href="{{route($config['route'],absolute:false)}}">{{$editing?'Cancel':'Reset'}}</a><button class="primary">{{$editing?'Update':'Save'}}</button>@endif</div></form></section>
<section class="pc-list"><h2>{{$config['title']}} List</h2><input class="pc-search" placeholder="Search..." oninput="filterPc(this)"><table id="pc-records"><thead><tr>@foreach($config['columns'] as $column)<th>{{$column}}</th>@endforeach</tr></thead><tbody>@forelse($records as $row)<tr><td>{{$row->id}}</td><td>{{$row->person_name?:$row->reference_no}}</td><td>{{$row->reference_no?:($row->form_date??'')}}</td><td>{{$row->total_score?:''}}</td><td>{{$row->grade?:''}}</td><td class="pc-actions"><a href="{{route($root.'.show',[$type,$row->id],false)}}"><i class="fa fa-eye"></i></a><a href="{{route($root.'.edit',[$type,$row->id],false)}}"><i class="fa fa-pencil"></i></a><form method="POST" action="{{route($root.'.destroy',[$type,$row->id],false)}}" onsubmit="return confirm('Delete this record?')">@csrf @method('DELETE')<button><i class="fa fa-times"></i></button></form></td></tr>@empty<tr><td colspan="{{count($config['columns'])}}" class="empty">No records found</td></tr>@endforelse</tbody></table></section></div>@endsection
@push('styles')<style>.pc-layout{display:grid;grid-template-columns:minmax(420px,1fr) minmax(0,2.2fr);gap:12px}.pc-form,.pc-list{background:#fff;border:1px solid #d2d9e2;box-shadow:0 1px 3px #0001}.pc-form h2,.pc-list h2{font-size:18px;font-weight:500;margin:0;padding:12px 14px;border-bottom:1px solid #d2d9e2}.pc-form form{padding:14px}.pc-field{margin-bottom:12px}.pc-field label{display:block;font-weight:600;font-size:13px;margin-bottom:5px}.pc-field label b{color:#dc3545}.pc-field>input,.pc-field>select,.pc-field>textarea{width:100%;box-sizing:border-box;border:1px solid #cbd5e1;padding:8px;font-size:13px}.pc-options{display:grid;grid-template-columns:1fr 1fr;gap:7px;font-size:13px}.score-table{overflow:auto}.score-table table{width:100%;border-collapse:collapse;font-size:11px}.score-table th,.score-table td{border:1px solid #d1d5db;padding:6px}.score-table th{background:#626262;color:#fff}.score-table td{text-align:center}.score-table td:nth-child(2),.score-table td:nth-child(3){text-align:left}.score-table input[type=number]{width:58px}.repeat-list>div{display:flex;gap:6px;margin-bottom:6px}.repeat-list input,.amount-grid input{padding:7px;border:1px solid #cbd5e1;min-width:0}.repeat-list input{flex:1}.amount-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.amount-grid input{width:100%;box-sizing:border-box}.pc-form-actions{display:flex;justify-content:flex-end;gap:7px;border-top:1px solid #eee;padding-top:12px}.pc-form-actions a,.pc-form-actions button{padding:7px 12px;border:1px solid #9ca3af;background:#fff;color:#333;text-decoration:none}.pc-form-actions .primary{background:#62676d;color:#fff}.pc-search{margin:10px 12px;width:220px;padding:8px;border:1px solid #b8c3d1;border-radius:5px}.pc-list{overflow:auto}.pc-list table{width:calc(100% - 24px);margin:0 12px 12px;border-collapse:collapse;font-size:12px}.pc-list th{background:#626262;color:#fff;padding:8px;border:1px solid #858585;white-space:nowrap}.pc-list td{padding:7px;border:1px solid #bdc7d3;white-space:nowrap}.pc-actions{white-space:nowrap}.pc-actions a,.pc-actions button{display:inline-flex;width:23px;height:23px;align-items:center;justify-content:center;border:1px solid #555;border-radius:5px;background:#666;color:#fff;margin-right:2px}.pc-actions a:nth-child(2){background:#fff;color:#555}.pc-actions button{background:#e53935;border-color:#c62828}.pc-actions form{display:inline}.pc-success{background:#d1e7dd;padding:8px}.empty{text-align:center}@media(max-width:900px){.pc-layout{grid-template-columns:1fr}.amount-grid,.pc-options{grid-template-columns:1fr}}</style>@endpush
@push('scripts')<script>function filterPc(i){const q=i.value.toLowerCase();document.querySelectorAll('#pc-records tbody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')}</script>@endpush
