@extends('admin.layouts.app')
@section('title',$config['title'])
@php $editing=$record&&!$viewMode;$payload=is_array($record?->payload)?$record->payload:[];$root=str_replace('.index','',$config['route']);$get=fn($n,$d='')=>old($n,$payload[$n]??($record->{$n}??$d));@endphp
@section('content')
<div class="pc-layout"><section class="pc-form"><h2>{{ $viewMode?'View ':($editing?'Edit ':'Add ') }}{{$config['title']}}</h2><form method="POST" action="{{$editing?route($root.'.update',[$type,$record->id],false):route($root.'.store',$type,false)}}">@csrf @if($editing)@method('PUT')@endif @if(session('success'))<div class="pc-success">{{session('success')}}</div>@endif
@foreach($config['fields'] as $field) @php $name=$field['name'];$current=$get($name); @endphp<div class="pc-field"><label>{{$field['label']}} @if($field['required']??false)<b>*</b>@endif</label>@switch($field['type'])
@case('staff')<select name="{{$name}}" @required($field['required']??false) @disabled($viewMode)><option value="">Select Staff</option>@foreach($staff as $person)@php $personName=trim($person->name.' '.$person->surname);@endphp<option value="{{$personName}}" @selected($current===$personName)>{{$personName}} @if($person->employee_id)({{$person->employee_id}})@endif</option>@endforeach</select>@break
@case('campus')<select name="{{$name}}" required @disabled($viewMode)><option value="">Select Campus</option>@foreach($campuses as $campus)<option value="{{$campus->id}}" @selected((string)$current===(string)$campus->id)>{{$campus->name}}</option>@endforeach</select>@break
@case('text') @case('date')<input type="{{$field['type']}}" name="{{$name}}" value="{{$current}}" @required($field['required']??false) @readonly($viewMode)>@break
@case('textarea')<textarea name="{{$name}}" rows="4" @readonly($viewMode)>{{$current}}</textarea>@break
@case('radio')<div class="pc-options">@foreach($field['options'] as $option)<label><input type="radio" name="{{$name}}" value="{{$option}}" @checked($current===$option) @disabled($viewMode)> {{$option}}</label>@endforeach</div>@break
@case('checks')<div class="pc-options">@foreach($field['options'] as $option)<label><input type="checkbox" name="{{$name}}[]" value="{{$option}}" @checked(in_array($option,(array)$current)) @disabled($viewMode)> {{$option}}</label>@endforeach</div>@break
@case('school_scores')<div class="score-table"><table><tr><th>Sr.</th><th>Domain / Area</th><th>Parameter</th><th colspan="5">Score 1-5</th></tr>@foreach(['Health Safety & Environment|School Front decorum','Health Safety & Environment|Security Measures','Health Safety & Environment|School Indoor Decorum/Material Organization','Admission & Withdrawal|Admission & Withdrawal Records & Reports','Internal & External Communication|Communication & Postage Records & Reports','Effective Management Meetings|Meetings Records & Reports','Events Management|Events Records & Reports','Customer Services Management|Inquiries and Complaints Records & Reports','Staff Recruitment Process|CVs Records','Staff Recruitment Process|Staff Official Records'] as $i=>$item)@php [$domain,$parameter]=explode('|',$item);$selected=$current[$i]??'';@endphp<tr><td>{{$i+1}}</td><td>{{$domain}}</td><td>{{$parameter}}</td>@for($s=1;$s<=5;$s++)<td><input type="radio" name="scores[{{$i}}]" value="{{$s}}" @checked((string)$selected===(string)$s) @disabled($viewMode)></td>@endfor</tr>@endforeach</table></div>@break
@case('annual_scores') @case('monthly_scores') @php $params=$field['type']==='annual_scores'?['Punctuality','Manners & Decorum','Neatness','Dressing','Good Appearance','Politeness in Talk','Obedience to Seniors','Classroom Management','Student Motivation','Teaching Quality']:['Punctuality','Manners','Neatness','Dressing','Appearance','Politeness','Obedience','Care','Cleanliness','Usage','Behavior','Team','Cooperation','Task','Results','Method'];$scores=$current['scores']??[];@endphp<div class="score-table"><table><tr><th>Parameter</th><th>Max</th><th>Score</th></tr>@foreach($params as $i=>$param)@php $max=$field['type']==='annual_scores'?50:($i%5===0?10:5);@endphp<tr><td>{{$param}}</td><td>{{$max}}</td><td><input type="number" name="{{$name}}[scores][{{$i}}]" value="{{$scores[$i]??''}}" min="0" max="{{$max}}" @readonly($viewMode)></td></tr>@endforeach</table></div>@break
@case('clearance_items')<div class="repeat-list">@foreach((array)$current as $i=>$item)<div><input name="clearance_items[{{$i}}][item]" placeholder="Item" value="{{$item['item']??''}}"><input name="clearance_items[{{$i}}][remarks]" placeholder="Remarks" value="{{$item['remarks']??''}}"><input type="date" name="clearance_items[{{$i}}][date]" value="{{$item['date']??''}}"></div>@endforeach<div><input name="clearance_items[0][item]" placeholder="Item"><input name="clearance_items[0][remarks]" placeholder="Remarks"><input type="date" name="clearance_items[0][date]"></div></div>@break
@case('amounts') @php $amounts=is_array($current)?$current:[];@endphp<div class="amount-grid">@foreach(['payable_amount','security_deposit','provident_bonus','deductible_amount','loan_availed','fine_penalty','applicable_taxes','assets_not_returned','fee_of_children','net_payable','net_receivable'] as $amount)<input name="amounts[{{$amount}}]" placeholder="{{ucwords(str_replace('_',' ',$amount))}}" value="{{$amounts[$amount]??''}}" @readonly($viewMode)>@endforeach</div>@break
@case('ratings') @php $statements=['Job was challenging','There were sufficient opportunities for advancement','Workload was manageable','Opportunities for training were available'];$ratings=$current['job_ratings']??[];@endphp<div class="score-table"><table><tr><th>Statement</th><th>Strongly Disagree</th><th>Disagree</th><th>Agree</th><th>Strongly Agree</th></tr>@foreach($statements as $i=>$statement)<tr><td>{{$statement}}</td>@for($s=1;$s<=4;$s++)<td><input type="radio" name="job_ratings[{{$i}}]" value="{{$s}}" @checked(($ratings[$i]??'')==$s) @disabled($viewMode)></td>@endfor</tr>@endforeach</table></div>@break
@case('repeat')<div class="repeat-list"><input name="{{$name}}[]" value="{{is_array($current)?($current[0]??''):$current}}" placeholder="Enter details" @readonly($viewMode)></div>@break
@endswitch</div>@endforeach
<div class="pc-form-actions">@if($viewMode)<a href="{{route($config['route'],absolute:false)}}">Back</a><a class="primary" href="{{route($root.'.edit',[$type,$record->id],false)}}">Edit</a>@else<a href="{{route($config['route'],absolute:false)}}">{{$editing?'Cancel':'Reset'}}</a><button class="primary">{{$editing?'Update':'Save'}}</button>@endif</div></form></section>
<section class="pc-list"><h2>{{$config['title']}} List</h2><input class="pc-search" placeholder="Search..." oninput="filterPc(this)"><table id="pc-records"><thead><tr>@foreach($config['columns'] as $column)<th>{{$column}}</th>@endforeach</tr></thead><tbody>@forelse($records as $row)<tr><td>{{$row->id}}</td><td>{{$row->person_name?:$row->reference_no}}</td><td>{{$row->reference_no?:($row->form_date??'')}}</td><td>{{$row->total_score?:''}}</td><td>{{$row->grade?:''}}</td><td class="pc-actions"><a href="{{route($root.'.show',[$type,$row->id],false)}}"><i class="fa fa-eye"></i></a><a href="{{route($root.'.edit',[$type,$row->id],false)}}"><i class="fa fa-pencil"></i></a><form method="POST" action="{{route($root.'.destroy',[$type,$row->id],false)}}" onsubmit="return confirm('Delete this record?')">@csrf @method('DELETE')<button><i class="fa fa-times"></i></button></form></td></tr>@empty<tr><td colspan="{{count($config['columns'])}}" class="empty">No records found</td></tr>@endforelse</tbody></table></section></div>@endsection
@push('scripts')<script>function filterPc(i){const q=i.value.toLowerCase();document.querySelectorAll('#pc-records tbody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')}</script>@endpush
