@extends('admin.layouts.app')

@section('title', 'TimeTable')

@section('content')
<section class="rounded border border-neutral-200 bg-white">
    <div class="flex flex-wrap items-center justify-between gap-2 border-b border-neutral-200 px-3 py-2"><form method="GET" action="{{ route('admin.academics.timetables.index', absolute: false) }}"><input name="search" value="{{ request('search') }}" class="rounded border border-neutral-300 px-3 py-1.5 text-sm" placeholder="Search..."></form><div class="flex items-center gap-1"><button type="button" data-table-export="copy" data-table="timetable-table" title="Copy" class="table-export-button"><i class="fa fa-copy"></i></button><button type="button" data-table-export="excel" data-table="timetable-table" title="Excel" class="table-export-button"><i class="fa fa-file-excel"></i></button><button type="button" data-table-export="csv" data-table="timetable-table" title="CSV" class="table-export-button"><i class="fa fa-file-csv"></i></button><a href="{{ route('admin.academics.timetables.pdf', request()->query(), false) }}" title="PDF" class="table-export-button"><i class="fa fa-file-pdf"></i></a><button type="button" data-table-export="print" data-table="timetable-table" title="Print" class="table-export-button"><i class="fa fa-print"></i></button><button type="button" data-table-columns="timetable-table" title="Columns" class="table-export-button"><i class="fa fa-table-columns"></i></button><button type="button" data-modal-open="timetable" class="rounded bg-blue-800 px-3 py-2 text-sm text-white"><i class="fa fa-plus"></i> Add</button></div></div>
    <div class="overflow-x-auto p-3"><table id="timetable-table" class="w-full text-left text-sm"><thead class="bg-blue-800 text-white"><tr><th class="cursor-pointer px-3 py-2">Branch ↕</th><th class="cursor-pointer px-3 py-2">Class ↕</th><th class="cursor-pointer px-3 py-2">Section ↕</th><th class="cursor-pointer px-3 py-2">Slot ↕</th><th class="cursor-pointer px-3 py-2">Subject ↕</th><th class="cursor-pointer px-3 py-2">Teacher ↕</th><th class="cursor-pointer px-3 py-2">Day ↕</th><th class="px-3 py-2">Action</th></tr></thead><tbody class="divide-y divide-neutral-200">@forelse($records as $record)<tr><td class="px-3 py-2">{{ $record->branch_name ?: '—' }}</td><td class="px-3 py-2">{{ $record->class_name ?: '—' }}</td><td class="px-3 py-2">{{ $record->section_name ?: '—' }}</td><td class="px-3 py-2">{{ $record->slot_name ?: ($record->period_name ?: $record->slot_id) }}@if($record->start_time)<small class="block text-neutral-500">{{ date('g:i A', strtotime($record->start_time)) }} - {{ date('g:i A', strtotime($record->end_time)) }}</small>@endif</td><td class="px-3 py-2">{{ $record->subject_name ?: '—' }}</td><td class="px-3 py-2">{{ $record->teacher_name ?: '—' }}</td><td class="px-3 py-2">{{ $record->day }}</td><td class="px-3 py-2"><form method="POST" action="{{ route('admin.academics.timetables.destroy', $record->id, absolute: false) }}" onsubmit="return confirm('Delete this timetable?')">@csrf @method('DELETE')<button class="rounded bg-red-600 px-2 py-1 text-white"><i class="fa fa-times"></i></button></form></td></tr>@empty<tr><td colspan="8" class="px-3 py-8 text-center text-neutral-500">No timetable found.</td></tr>@endforelse</tbody></table><div class="flex justify-between pt-2 text-xs text-neutral-600"><span>Records: {{ $records->count() ? 1 : 0 }} to {{ $records->count() }} of {{ $records->count() }}</span><span class="list-pagination"><button type="button" disabled aria-label="Previous page"><i class="fa fa-angle-left"></i></button><span>1</span><button type="button" disabled aria-label="Next page"><i class="fa fa-angle-right"></i></button></span></div></div>
</section>

<section data-modal="timetable" class="admin-modal {{ $errors->any() ? 'is-open' : '' }}"><div class="admin-modal-panel time-table-modal rounded border border-neutral-200 bg-white"><div class="flex items-center justify-between border-b border-neutral-200 px-4 py-3"><h2 class="text-lg font-medium">Add Timetable</h2><button type="button" class="admin-modal-close" data-modal-close="timetable">&times;</button></div><form method="POST" action="{{ route('admin.academics.timetables.store', absolute: false) }}" class="grid gap-4 p-4 md:grid-cols-3">@csrf
<div><label class="mb-1 block text-sm">Branch <span class="required-mark">*</span></label><select id="timetable-branch" name="brc_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($branches as $item)<option value="{{ $item->id }}" @selected((string)old('brc_id', $branchId) === (string)$item->id)>{{ $item->name }}</option>@endforeach</select></div>
<div><label class="mb-1 block text-sm">Class <span class="required-mark">*</span></label><select name="class_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($classes as $item)<option value="{{ $item->id }}" @selected((string)old('class_id') === (string)$item->id)>{{ $item->class }}</option>@endforeach</select></div>
<div><label class="mb-1 block text-sm">Section <span class="required-mark">*</span></label><select name="section_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($sections as $item)<option value="{{ $item->id }}" @selected((string)old('section_id') === (string)$item->id)>{{ $item->section }}</option>@endforeach</select></div>
<div><label class="mb-1 block text-sm">Slot <span class="required-mark">*</span></label><select id="timetable-slot" name="slot_id" data-slots-url="{{ route('admin.academics.timetables.slots', ['branchId' => '__BRANCH__'], false) }}" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($slots as $item)<option value="{{ $item->id }}" @selected((string)old('slot_id') === (string)$item->id)>{{ $item->slot }} ({{ date('g:i A', strtotime($item->start_time)) }} - {{ date('g:i A', strtotime($item->end_time)) }})</option>@endforeach</select>@if($slots->isEmpty())<p class="mt-1 text-xs text-red-600">No time allocation slot found for this branch.</p>@endif</div>
<div><label class="mb-1 block text-sm">Subject <span class="required-mark">*</span></label><select name="subject_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($subjects as $item)<option value="{{ $item->id }}" @selected((string)old('subject_id') === (string)$item->id)>{{ $item->name }}{{ $item->code ? ' ('.$item->code.')' : '' }}</option>@endforeach</select></div>
<div><label class="mb-1 block text-sm">Teacher <span class="required-mark">*</span></label><select name="staff_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($teachers as $item)<option value="{{ $item->id }}" @selected((string)old('staff_id') === (string)$item->id)>{{ trim($item->name.' '.$item->surname) }}</option>@endforeach</select></div>
<fieldset class="md:col-span-3"><legend class="mb-2 text-sm">Days <span class="required-mark">*</span></legend><div class="flex flex-wrap gap-x-5 gap-y-2">@foreach(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'] as $day)<label class="mr-1 flex items-center gap-1 text-sm"><input type="checkbox" name="days[]" value="{{ $day }}" @checked(in_array($day, old('days', ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'])))> {{ $day }}</label>@endforeach</div></fieldset>
<div class="flex justify-end md:col-span-3"><button class="rounded bg-blue-800 px-4 py-2 text-sm text-white">Save</button></div></form></div></section>
@endsection
