@extends('admin.layouts.app')

@section('title', 'Time Allocation')

@section('content')
<section class="rounded border border-neutral-200 bg-white">
    <div class="flex items-center justify-between border-b border-neutral-200 px-4 py-3"><h2 class="text-lg font-medium">Time Allocation List</h2><button type="button" data-modal-open="time-allocation" class="rounded bg-blue-800 px-3 py-2 text-sm text-white"><i class="fa fa-plus"></i> Add</button></div>
    <div class="flex flex-wrap items-center justify-between gap-2 border-b border-neutral-200 px-3 py-2"><input type="search" data-table-search="time-allocation-table" placeholder="Search..." class="rounded border border-neutral-300 px-3 py-1.5 text-sm"><div class="flex gap-1"><button type="button" data-table-export="copy" data-table="time-allocation-table" title="Copy" class="table-export-button"><i class="fa fa-copy"></i></button><button type="button" data-table-export="excel" data-table="time-allocation-table" title="Excel" class="table-export-button"><i class="fa fa-file-excel"></i></button><button type="button" data-table-export="csv" data-table="time-allocation-table" title="CSV" class="table-export-button"><i class="fa fa-file-csv"></i></button><a href="{{ route('admin.academics.time-allocation.pdf', request()->query(), false) }}" title="PDF" class="table-export-button"><i class="fa fa-file-pdf"></i></a><button type="button" data-table-export="print" data-table="time-allocation-table" title="Print" class="table-export-button"><i class="fa fa-print"></i></button><button type="button" data-table-columns="time-allocation-table" title="Columns" class="table-export-button"><i class="fa fa-table-columns"></i></button></div></div>
    <div class="overflow-x-auto p-3"><table id="time-allocation-table" class="w-full text-left text-sm"><thead class="bg-blue-800 text-white"><tr><th class="cursor-pointer px-3 py-2">Branch ▼</th><th class="cursor-pointer px-3 py-2">Class ▼</th><th class="cursor-pointer px-3 py-2">Slot ▼</th><th class="cursor-pointer px-3 py-2">Slot Type ▼</th><th class="cursor-pointer px-3 py-2">Wing/Shift ▼</th><th class="cursor-pointer px-3 py-2">Time From ▼</th><th class="cursor-pointer px-3 py-2">Time To ▼</th><th class="cursor-pointer px-3 py-2">Friday Time From ▼</th><th class="cursor-pointer px-3 py-2">Friday Time To ▼</th><th class="px-3 py-2">Action</th></tr></thead><tbody class="divide-y divide-neutral-200">@forelse($records as $record)<tr><td class="px-3 py-2">{{ $record->branch_name }}</td><td class="px-3 py-2">{{ $record->class_name ?: '-' }}</td><td class="px-3 py-2">{{ $record->slot }}</td><td class="px-3 py-2">{{ $slotTypes[$record->slot_type] ?? 'Regular Period' }}</td><td class="px-3 py-2">{{ $wingShifts[$record->wing_shift] ?? '-' }}</td><td class="px-3 py-2">{{ date('g:i A', strtotime($record->start_time)) }}</td><td class="px-3 py-2">{{ date('g:i A', strtotime($record->end_time)) }}</td><td class="px-3 py-2">{{ date('g:i A', strtotime($record->f_start_time)) }}</td><td class="px-3 py-2">{{ date('g:i A', strtotime($record->f_end_time)) }}</td><td class="px-3 py-2"><form method="POST" action="{{ route('admin.academics.time-allocation.destroy', $record->id, absolute: false) }}" onsubmit="return confirm('Delete this allocation?')">@csrf @method('DELETE')<button class="rounded bg-red-600 px-2 py-1 text-white"><i class="fa fa-times"></i></button></form></td></tr>@empty<tr><td colspan="10" class="px-3 py-8 text-center text-neutral-500">No time allocation found.</td></tr>@endforelse</tbody></table><div class="flex justify-between pt-2 text-xs text-neutral-600"><span>Records: {{ $records->count() ? 1 : 0 }} to {{ $records->count() }} of {{ $records->count() }}</span><span>‹　›</span></div></div>
</section>

<section data-modal="time-allocation" class="admin-modal"><div class="admin-modal-panel time-allocation-modal rounded border border-neutral-200 bg-white"><div class="flex items-center justify-between border-b border-neutral-200 px-4 py-3"><h2 class="text-lg font-medium">Add Time Allocation</h2><button type="button" class="admin-modal-close" data-modal-close="time-allocation">&times;</button></div><form method="POST" action="{{ route('admin.academics.time-allocation.store', absolute: false) }}" class="grid gap-4 p-4 md:grid-cols-2">@csrf
<div><label class="mb-1 block text-sm">Branch <span class="required-mark">*</span></label><select name="brc_id" required class="w-full rounded border border-neutral-300 px-3 py-2">@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string)$branchId === (string)$branch->id)>{{ $branch->name }}</option>@endforeach</select></div>
<div><label class="mb-1 block text-sm">Class <span class="required-mark">*</span></label><select name="class_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($classes as $class)<option value="{{ $class->id }}">{{ $class->class }}</option>@endforeach</select></div>
<div><label class="mb-1 block text-sm">Period</label><select name="period_id" class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($periods as $period)<option value="{{ $period->id }}">{{ $period->name }}</option>@endforeach</select></div>
<div><label class="mb-1 block text-sm">Slot <span class="required-mark">*</span></label><input name="slot" required class="w-full rounded border border-neutral-300 px-3 py-2"></div>
<div><label class="mb-1 block text-sm">Slot Type <span class="required-mark">*</span></label><select name="slot_type" required class="w-full rounded border border-neutral-300 px-3 py-2">@foreach($slotTypes as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div>
<div><label class="mb-1 block text-sm">Wing / Shift</label><select name="wing_shift" class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($wingShifts as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div>
<div class="md:col-span-2"><label class="mb-1 block text-sm">Applies to</label><div class="flex flex-wrap gap-3 text-sm">@foreach(['Monday','Tuesday','Wednesday','Thursday'] as $day)<label class="inline-flex items-center gap-1"><input type="checkbox" name="applies_days[]" value="{{ $day }}"> {{ $day }}</label>@endforeach</div><p class="mt-1 text-xs text-neutral-500">Leave empty for the whole week.</p></div>
<div><label class="mb-1 block text-sm">Special Schedule</label><select name="special_schedule" class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">None</option><option value="friday">Friday</option><option value="half_day">Half-Day</option></select></div>
<div><label class="mb-1 block text-sm">Time From <span class="required-mark">*</span></label><input type="time" name="time_from" data-time-picker data-duration-from required class="w-full rounded border border-neutral-300 px-3 py-2"></div><div><label class="mb-1 block text-sm">Time To <span class="required-mark">*</span></label><input type="time" name="time_to" data-time-picker data-duration-to required class="w-full rounded border border-neutral-300 px-3 py-2"><span data-duration-badge class="mt-1 inline-block text-xs text-blue-800"></span></div>
<div><label class="mb-1 block text-sm">Friday Time From <span class="required-mark">*</span></label><input type="time" name="f_time_from" data-time-picker required class="w-full rounded border border-neutral-300 px-3 py-2"></div><div><label class="mb-1 block text-sm">Friday Time To <span class="required-mark">*</span></label><input type="time" name="f_time_to" data-time-picker required class="w-full rounded border border-neutral-300 px-3 py-2"></div>
<div class="flex justify-end md:col-span-2"><button class="rounded bg-blue-800 px-4 py-2 text-sm text-white">Save</button></div></form></div></section>
@endsection
