@extends('admin.layouts.app')
@section('title', 'Syllabus Directory')
@section('content')
<section id="directory-criteria-modal" class="mb-4 rounded border border-neutral-200 bg-white"><div><div class="border-b border-neutral-200 px-4 py-3"><h2 class="text-lg font-medium">Select Criteria</h2></div>
<form method="GET" action="{{ route('admin.academics.syllabus-directory.index', absolute: false) }}" class="p-4"><input type="hidden" name="searched" value="1"><div class="grid gap-4 md:grid-cols-3 xl:grid-cols-6">
<div><label class="mb-1 block text-sm">Branch <span class="text-red-600">*</span></label><select id="directory-branch" name="brc_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($branches as $item)<option value="{{ $item->id }}" @selected((string)($selected['brc_id'] ?? '') === (string)$item->id)>{{ $item->name }}</option>@endforeach</select></div>
<div><label class="mb-1 block text-sm">Term <span class="text-red-600">*</span></label><select name="term_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($terms as $item)<option value="{{ $item->id }}" @selected((string)($selected['term_id'] ?? '') === (string)$item->id)>{{ $item->name }}</option>@endforeach</select></div>
<div><label class="mb-1 block text-sm">Months <span class="text-red-600">*</span></label><select name="month_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($months as $id => $item)<option value="{{ $id }}" @selected((string)($selected['month_id'] ?? '') === (string)$id)>{{ $item }}</option>@endforeach</select></div>
<div><label class="mb-1 block text-sm">Class <span class="text-red-600">*</span></label><select id="directory-class" name="class_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($classes as $item)<option value="{{ $item->id }}" @selected((string)($selected['class_id'] ?? '') === (string)$item->id)>{{ $item->class }}</option>@endforeach</select></div>
<div><label class="mb-1 block text-sm">Section <span class="text-red-600">*</span></label><select id="directory-section" name="section_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($sections as $item)<option value="{{ $item->id }}" @selected((string)($selected['section_id'] ?? '') === (string)$item->id)>{{ $item->section }}</option>@endforeach</select></div>
<div><label class="mb-1 block text-sm">Subject <span class="text-red-600">*</span></label><select id="directory-subject" name="subject_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($subjects as $item)<option value="{{ $item->id }}" @selected((string)($selected['subject_id'] ?? '') === (string)$item->id)>{{ $item->name }} ({{ $item->code }})</option>@endforeach</select></div>
</div><div class="mt-4 flex justify-end"><button class="rounded bg-blue-800 px-4 py-2 text-sm text-white hover:bg-blue-700"><i class="fa fa-search"></i> Search</button></div></form></div></section>
@if(request()->boolean('searched'))
<div class="syllabus-directory-toolbar"><input type="search" data-table-search="directory-results" placeholder="Search..." class="rounded border border-neutral-300 px-3 py-2"><div class="flex gap-1"><button type="button" data-table-export="copy" data-table="directory-results" title="Copy"><i class="fa fa-copy"></i></button><button type="button" data-table-export="excel" data-table="directory-results" title="Excel"><i class="fa fa-file-excel"></i></button><button type="button" data-table-export="csv" data-table="directory-results" title="CSV"><i class="fa fa-file-csv"></i></button><a href="{{ route('admin.academics.syllabus.pdf', request()->query(), false) }}" title="PDF"><i class="fa fa-file-pdf"></i></a><button type="button" data-table-export="print" data-table="directory-results" title="Print"><i class="fa fa-print"></i></button><button type="button" data-table-columns="directory-results" title="Columns"><i class="fa fa-table-columns"></i></button></div></div>
<section class="mt-4 overflow-x-auto rounded border border-neutral-200 bg-white"><div class="flex items-center justify-between border-b border-neutral-200 px-4 py-3"><h2 class="text-lg font-medium">Syllabus Status</h2>@if($records->isNotEmpty())<a href="{{ route('admin.academics.syllabus.pdf', request()->query(), false) }}" class="rounded bg-orange-500 px-3 py-2 text-sm text-white hover:bg-orange-600"><i class="fa fa-download"></i> Download PDF</a>@endif</div><table id="directory-results" class="w-full text-left text-sm"><thead class="bg-blue-800 text-white"><tr><th class="cursor-pointer px-3 py-2">Class ▼</th><th class="cursor-pointer px-3 py-2">Term ▼</th><th class="cursor-pointer px-3 py-2">Month ▼</th><th class="cursor-pointer px-3 py-2">Subject ▼</th><th class="cursor-pointer px-3 py-2">Syllabus ▼</th><th class="px-3 py-2">Action</th></tr></thead><tbody class="divide-y divide-neutral-200">@forelse($records as $record)<tr><td class="px-3 py-2">{{ $record->class_name }} - {{ $record->section_name }}</td><td class="px-3 py-2">{{ $record->term_name }}</td><td class="px-3 py-2">{{ $months[$record->month_id] ?? $record->month_id }}</td><td class="px-3 py-2">{{ $record->subject_name }}</td><td class="max-w-md px-3 py-2">{{ strip_tags((string)$record->presentation) }}</td><td class="px-3 py-2"><form method="POST" action="{{ route('admin.academics.syllabus.destroy', $record->id, false) }}" onsubmit="return confirm('Delete this syllabus?')">@csrf @method('DELETE')<button class="rounded bg-red-500 px-2 py-1 text-white" title="Delete"><i class="fa fa-times"></i></button></form></td></tr>@empty<tr><td colspan="6" class="px-3 py-8 text-center text-neutral-500">No syllabus found for the selected criteria.</td></tr>@endforelse</tbody></table><div class="px-3 py-2 text-xs text-neutral-600">Records: {{ $records->count() ? 1 : 0 }} to {{ $records->count() }} of {{ $records->count() }}</div></section>
@endif
@endsection
@push('scripts')
<script>
(function () { const cls=document.getElementById('directory-class'), section=document.getElementById('directory-section'), subject=document.getElementById('directory-subject'); if(!cls||!section||!subject)return; const selectedSection=@json($selected['section_id']??''), selectedSubject=@json($selected['subject_id']??''); const fill=(select,data,subjectMode,selected)=>{select.innerHTML='<option value="">Select</option>';data.forEach(item=>{const option=document.createElement('option');option.value=item.id;option.textContent=subjectMode?`${item.name} (${item.code})`:item.section;option.selected=String(item.id)===String(selected);select.appendChild(option);});}; const load=(keep=false)=>{if(!cls.value)return;section.disabled=true;subject.disabled=true;section.innerHTML='<option>Loading...</option>';subject.innerHTML='<option>Loading...</option>';fetch('{{ route('admin.academics.syllabus.options', absolute: false) }}?class_id='+encodeURIComponent(cls.value),{headers:{Accept:'application/json'}}).then(r=>{if(!r.ok)throw new Error('Options could not be loaded');return r.json();}).then(data=>{fill(section,data.sections||[],false,keep?selectedSection:'');fill(subject,data.subjects||[],true,keep?selectedSubject:'');}).catch(()=>{section.innerHTML='<option value="">Unable to load sections</option>';subject.innerHTML='<option value="">Unable to load subjects</option>';}).finally(()=>{section.disabled=false;subject.disabled=false;});}; cls.addEventListener('change',()=>load(false));if(cls.value&&(section.options.length<=1||subject.options.length<=1))load(true); document.querySelectorAll('#directory-results th.cursor-pointer').forEach((header,index)=>header.addEventListener('click',()=>{const table=header.closest('table'),body=table.tBodies[0],rows=[...body.rows],ascending=header.dataset.order!=='asc';table.querySelectorAll('th').forEach(h=>h.dataset.order='');header.dataset.order=ascending?'asc':'desc';header.textContent=header.textContent.replace(/[\u25bc\u25b2]/g,'').trim()+(ascending?' \u25b2':' \u25bc');rows.sort((a,b)=>(a.cells[index]?.innerText||'').localeCompare(b.cells[index]?.innerText||'',undefined,{numeric:true,sensitivity:'base'})*(ascending?1:-1));rows.forEach(row=>body.appendChild(row));})); })();
</script>
@endpush
