@php
    $subject = $subject ?? null;
    $subjectGroup = $subjectGroup ?? null;
    $chapter = $chapter ?? null;
    $topic = $topic ?? null;
    $term = $term ?? null;
    $week = $week ?? null;
    $day = $day ?? null;
    $setting = $term ?? $week ?? $day;
    $edit = $subject ?? $subjectGroup ?? $chapter ?? $topic ?? $setting ?? null;
    $titles = ['subjects'=>'Subject','subject-groups'=>'Subject Group','chapters'=>'Chapter','topics'=>'Topic','term-settings'=>'Term','week-settings'=>'Week','day-settings'=>'Day'];
    $title = $titles[$kind];
    $routeBase = ['subjects'=>'subjects','subject-groups'=>'subject-groups','chapters'=>'chapters','topics'=>'topics','term-settings'=>'term-settings','week-settings'=>'week-settings','day-settings'=>'day-settings'][$kind];
@endphp
@if($kind === 'subjects')
@push('styles')
<link rel="stylesheet" href="{{ asset('assets/css/curriculum-subject-modal.css') }}">
@endpush
@endif
@push('scripts')
<script>(function(){const headers=[...document.querySelectorAll('#curriculum-table th.cursor-pointer')];headers.forEach(h=>{h.dataset.asc='1';h.textContent=h.textContent.replace(/[\u2195\u2191\u2193]|â†•/g,'').trim()+' ↑';h.addEventListener('click',()=>{const up=h.dataset.asc==='1';h.textContent=h.textContent.replace(/[\u2195\u2191\u2193]|â†•/g,'').trim()+(up?' ↓':' ↑')})})})();</script>
@endpush
@if(false && in_array($kind,['term-settings','week-settings','day-settings'],true))
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function () {
    const table = document.getElementById('curriculum-table');
    if (!table?.tHead) return;
    table.tHead.innerHTML = '<tr><th class="cursor-pointer px-3 py-2">Name ▼</th><th class="px-3 py-2">Action</th></tr>';
});
</script>
@endpush
@endif
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function () {
    const rows = document.getElementById('name-rows');
    const add = document.getElementById('add-name');
    if (!rows || !add) return;

    const syncRemoveButtons = function () {
        const allRows = rows.querySelectorAll('.name-row');
        allRows.forEach((row, index) => {
            row.querySelector('.remove-name')?.classList.toggle('hidden', allRows.length === 1 || index === 0);
        });
    };

    add.addEventListener('click', function () {
        window.setTimeout(function () {
            const newRow = rows.lastElementChild;
            if (!newRow || newRow.querySelector('.remove-name')) return syncRemoveButtons();
            newRow.classList.remove('grid-cols-2');
            newRow.classList.add('name-row', 'curriculum-name-row');
            newRow.insertAdjacentHTML('beforeend', '<button type="button" class="remove-name mb-1 h-6 w-6 rounded bg-red-600 text-white" aria-label="Remove">&times;</button>');
            syncRemoveButtons();
        }, 0);
    });

    rows.addEventListener('click', function (event) {
        const button = event.target.closest('.remove-name');
        if (!button || rows.querySelectorAll('.name-row').length <= 1) return;
        button.closest('.name-row').remove();
        syncRemoveButtons();
    });
    syncRemoveButtons();
});
</script>
@endpush
<div class="curriculum-print-page grid gap-4 lg:grid-cols-3">
    <section id="curriculum-form-modal" class="curriculum-print-hide admin-modal {{ (($edit || request()->filled('class_id') || request()->filled('subject_id')) && !session('success') && !session('error')) ? 'is-open' : '' }}" data-modal="curriculum-form">
        <div class="admin-modal-panel {{ $kind === 'subjects' ? 'curriculum-compact-modal' : '' }} {{ $kind === 'subject-groups' ? 'curriculum-group-modal' : '' }} rounded border border-neutral-200 bg-white p-4">
        <div class="mb-4 flex items-center justify-between border-b border-neutral-200 pb-3"><h2 class="text-lg font-medium">{{ $edit ? 'Edit '.$title : 'Add '.$title }}</h2><button type="button" class="admin-modal-close" data-modal-close="curriculum-form" aria-label="Close">&times;</button></div>
        <form method="POST" action="{{ $edit ? route('admin.academics.'.$routeBase.'.update',$edit) : route('admin.academics.'.$routeBase.'.store') }}" class="space-y-4">
            @csrf @if($edit) @method('PUT') @endif
            @if(in_array($kind,['term-settings','week-settings','day-settings'],true))
                <div><label class="mb-1 block text-sm">Name <span class="text-red-600">*</span></label><input name="name" value="{{ old('name',$setting?->name) }}" required class="w-full rounded border border-neutral-300 px-3 py-2">@error('name')<p class="text-sm text-red-600">{{ $message }}</p>@enderror</div>
                @if($kind==='term-settings')<div class="grid gap-3 sm:grid-cols-2"><div><label class="mb-1 block text-sm">Start Date</label><input type="date" data-date-picker name="start_date" value="{{ old('start_date',$setting?->start_date?->format('Y-m-d')) }}" class="date-picker-input w-full rounded border border-neutral-300 px-3 py-2"></div><div><label class="mb-1 block text-sm">End Date</label><input type="date" data-date-picker name="end_date" value="{{ old('end_date',$setting?->end_date?->format('Y-m-d')) }}" class="date-picker-input w-full rounded border border-neutral-300 px-3 py-2"></div></div><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',in_array(strtolower((string)($setting?->is_active ?? 'yes')),['1','yes','active'],true)))> Active Term</label>@endif
                @if($kind==='week-settings')<div><label class="mb-1 block text-sm">Term <span class="text-red-600">*</span></label><select name="term_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($terms ?? [] as $item)<option value="{{ $item->id }}" @selected((string)old('term_id',$setting?->term_id)===(string)$item->id)>{{ $item->name }}</option>@endforeach</select></div><div class="grid gap-3 sm:grid-cols-2"><div><label class="mb-1 block text-sm">Start Date</label><input type="date" data-date-picker name="start_date" value="{{ old('start_date',$setting?->start_date?->format('Y-m-d')) }}" class="date-picker-input w-full rounded border border-neutral-300 px-3 py-2"></div><div><label class="mb-1 block text-sm">End Date</label><input type="date" data-date-picker name="end_date" value="{{ old('end_date',$setting?->end_date?->format('Y-m-d')) }}" class="date-picker-input w-full rounded border border-neutral-300 px-3 py-2"></div></div><div class="flex gap-4 text-sm"><label class="flex items-center gap-2"><input type="checkbox" name="is_holiday" value="1" @checked(old('is_holiday',$setting?->is_holiday))> Holiday Week</label><label class="flex items-center gap-2"><input type="checkbox" name="is_exam" value="1" @checked(old('is_exam',$setting?->is_exam))> Exam Week</label></div>@endif
                @if($kind==='day-settings')<div class="grid gap-3 sm:grid-cols-2"><div><label class="mb-1 block text-sm">Term <span class="text-red-600">*</span></label><select name="term_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($terms ?? [] as $item)<option value="{{ $item->id }}" @selected((string)old('term_id',$setting?->term_id)===(string)$item->id)>{{ $item->name }}</option>@endforeach</select></div><div><label class="mb-1 block text-sm">Week <span class="text-red-600">*</span></label><select name="week_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($weeks ?? [] as $item)<option value="{{ $item->id }}" @selected((string)old('week_id',$setting?->week_id)===(string)$item->id)>{{ $item->name }}</option>@endforeach</select></div></div><div class="grid gap-3 sm:grid-cols-2"><div><label class="mb-1 block text-sm">Date</label><input type="date" data-date-picker name="date" value="{{ old('date',$setting?->date?->format('Y-m-d')) }}" class="date-picker-input w-full rounded border border-neutral-300 px-3 py-2"></div><div><label class="mb-1 block text-sm">Period</label><input name="period" value="{{ old('period',$setting?->period) }}" placeholder="e.g. 1st Period" class="w-full rounded border border-neutral-300 px-3 py-2"></div></div><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_working_day" value="1" @checked(old('is_working_day',$setting?->is_working_day ?? true))> Working Day</label>@endif
                <div><label class="mb-1 block text-sm">Description</label><textarea name="description" rows="3" class="w-full rounded border border-neutral-300 px-3 py-2">{{ old('description',$setting?->note) }}</textarea>@error('description')<p class="text-sm text-red-600">{{ $message }}</p>@enderror</div>
            @elseif($kind==='subjects')
                <div><label class="mb-1 block text-sm">Subject Name <span class="text-red-600">*</span></label><input name="name" value="{{ old('name',$subject?->name) }}" required class="w-full rounded border border-neutral-300 px-3 py-2">@error('name')<p class="text-sm text-red-600">{{ $message }}</p>@enderror</div>
                <div class="curriculum-subject-type"><label><input type="radio" name="type" value="theory" @checked(old('type',$subject?->type)==='theory') required> Theory</label><label><input type="radio" name="type" value="practical" @checked(old('type',$subject?->type)==='practical')> Practical</label></div>
                <div class="curriculum-subject-code"><label class="mb-1 block text-sm">Subject Code <span class="text-red-600">*</span></label><input name="code" value="{{ old('code',$subject?->code) }}" required class="w-full rounded border border-neutral-300 px-3 py-2">@error('code')<p class="text-sm text-red-600">{{ $message }}</p>@enderror</div>
            @elseif($kind==='subject-groups')
                <div><label class="mb-1 block text-sm">Class <span class="text-red-600">*</span></label><select name="class_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($classes as $c)<option value="{{ $c->id }}" @selected((string)old('class_id',$subjectGroup?->class_id)===(string)$c->id)>{{ $c->class }}</option>@endforeach</select>@error('class_id')<p class="text-sm text-red-600">{{ $message }}</p>@enderror</div>
                <div><label class="mb-1 block text-sm">Name <span class="text-red-600">*</span></label><input name="name" value="{{ old('name',$subjectGroup?->name) }}" required class="w-full rounded border border-neutral-300 px-3 py-2">@error('name')<p class="text-sm text-red-600">{{ $message }}</p>@enderror</div>
                <div><label class="mb-1 block text-sm">Subjects <span class="text-red-600">*</span></label>@foreach($subjects as $s)<label class="block py-1 text-sm"><input type="checkbox" name="subjects[]" value="{{ $s->id }}" @checked(in_array($s->id,old('subjects',$subjectGroup?->subjects?->pluck('id')->all()??[])))> {{ $s->name }} ({{ $s->code }})</label>@endforeach</div>
                <div><label class="mb-1 block text-sm">Description</label><textarea name="description" rows="3" class="w-full rounded border border-neutral-300 px-3 py-2">{{ old('description',$subjectGroup?->description) }}</textarea></div>
            @elseif($kind==='chapters' || $kind==='topics')
                <div><label class="mb-1 block text-sm">Class <span class="text-red-600">*</span></label><select id="curriculum-class" name="class_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($classes as $c)<option value="{{ $c->id }}" @selected((string)old('class_id',$selectedClass)===(string)$c->id)>{{ $c->class }}</option>@endforeach</select></div>
                <div><label class="mb-1 block text-sm">Subject <span class="text-red-600">*</span></label><select id="curriculum-subject" name="subject_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($subjects as $s)<option value="{{ $s->id }}" @selected((string)old('subject_id',$selectedSubject ?? ($topic?->subject_id ?? (($chapter ?? null)?->subject_id)))===(string)$s->id)>{{ $s->name }} ({{ $s->code }})</option>@endforeach</select></div>
                @if($kind==='topics')<div><label class="mb-1 block text-sm">Chapter <span class="text-red-600">*</span></label><select name="chapter_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($chapters as $co)<option value="{{ $co->id }}" @selected((string)old('chapter_id',$topic?->chapter_id)===(string)$co->id)>{{ $co->name }} @if($co->urdu) / {{ $co->urdu }} @endif</option>@endforeach</select></div>@endif
                <div id="name-rows" class="space-y-3">@php($eng=old('eng_name',$edit ? [$edit->name] : [''])) @php($urd=old('urdu_name',$edit ? [$edit->urdu] : [''])) @foreach($eng as $i=>$v)<div class="name-row grid grid-cols-[1fr_1fr_auto] items-end gap-2"><div><label class="mb-1 block text-sm">{{ $kind==='chapters' ? 'Chapter Name in English' : 'Topic Name in English' }} @if($i===0)<span class="text-red-600">*</span>@endif</label><input name="eng_name[]" value="{{ $v }}" required class="w-full rounded border border-neutral-300 px-3 py-2"></div><div><label class="mb-1 block text-sm">{{ $kind==='chapters' ? 'Chapter Name in Urdu' : 'Topic Name in Urdu' }}</label><input name="urdu_name[]" value="{{ $urd[$i]??'' }}" class="w-full rounded border border-neutral-300 px-3 py-2"></div><button type="button" class="remove-name {{ $i===0 ? 'hidden' : '' }} mb-1 h-6 w-6 rounded bg-red-600 text-white" aria-label="Remove">&times;</button></div>@endforeach</div><div class="flex justify-end gap-2"><button type="button" id="add-name" class="rounded bg-blue-600 px-3 py-1 text-sm text-white">+ Add More</button><button type="button" data-modal-open="curriculum-import" class="rounded bg-blue-600 px-3 py-1 text-sm text-white">Import</button></div>
            @endif
            <div class="flex justify-end gap-2 border-t border-neutral-200 pt-3">@if($edit)<a href="{{ route('admin.academics.'.$routeBase.'.index') }}" class="rounded border border-neutral-300 px-4 py-2">Cancel</a>@endif<button class="rounded bg-blue-600 px-4 py-2 text-white">{{ $edit?'Update':'Save' }}</button></div>
        </form>
        </div>
    </section>
    @if(in_array($kind,['chapters','topics'],true))
    <section class="admin-modal curriculum-print-hide" data-modal="curriculum-import">
        <div class="admin-modal-panel rounded border border-neutral-200 bg-white p-4">
            <div class="mb-4 flex items-center justify-between border-b border-neutral-200 pb-3"><h2 class="text-lg font-medium">Import {{ $title }}s</h2><button type="button" class="admin-modal-close" data-modal-close="curriculum-import" aria-label="Close">&times;</button></div>
            <form method="POST" enctype="multipart/form-data" action="{{ route('admin.academics.'.$routeBase.'.import') }}" class="space-y-4">
                @csrf
                <div><label class="mb-1 block text-sm">Class <span class="text-red-600">*</span></label><select id="curriculum-import-class" name="class_id" data-subject-url="{{ $kind==='chapters' ? route('admin.academics.chapters.subjects', ['classId' => '__CLASS__'], false) : route('admin.academics.topics.subjects', ['classId' => '__CLASS__'], false) }}" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($classes as $c)<option value="{{ $c->id }}" @selected((string)($selectedClass??'')===(string)$c->id)>{{ $c->class }}</option>@endforeach</select></div>
                <div><label class="mb-1 block text-sm">Subject <span class="text-red-600">*</span></label><select id="curriculum-import-subject" name="subject_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($subjects as $s)<option value="{{ $s->id }}" @selected((string)($selectedSubject??'')===(string)$s->id)>{{ $s->name }} ({{ $s->code }})</option>@endforeach</select></div>
                @if($kind==='topics')<div><label class="mb-1 block text-sm">Chapter <span class="text-red-600">*</span></label><select name="chapter_id" required class="w-full rounded border border-neutral-300 px-3 py-2"><option value="">Select</option>@foreach($chapters as $co)<option value="{{ $co->id }}">{{ $co->name }} @if($co->urdu) / {{ $co->urdu }} @endif</option>@endforeach</select></div>@endif
                <div><label class="mb-1 block text-sm">CSV File <span class="text-red-600">*</span></label><input type="file" name="file" accept=".csv,.txt" required class="syllabus-file-input w-full rounded border border-neutral-300 px-3 py-2"><p class="mt-1 text-xs text-neutral-500">First column: English name. Second column: Urdu name (optional).</p></div>
                <div class="flex justify-end border-t border-neutral-200 pt-3"><button class="rounded bg-blue-600 px-4 py-2 text-white">Import</button></div>
            </form>
        </div>
    </section>
    @endif
    <section class="curriculum-print-section rounded border border-neutral-200 bg-white p-4 lg:col-span-3">
    @if(in_array($kind,['term-settings','week-settings','day-settings'],true))
        <div class="curriculum-toolbar curriculum-print-hide mb-3"><h2 class="text-lg font-medium">{{ $title }} List</h2><div class="curriculum-toolbar-controls"><form><input name="search" value="{{ request('search') }}" placeholder="Search..." class="rounded border border-neutral-300 px-3 py-2"></form><button type="button" data-export="copy" class="h-8 w-8 rounded bg-blue-800 text-white" title="Copy"><i class="fa fa-copy"></i></button><button type="button" data-export="excel" class="h-8 w-8 rounded bg-blue-800 text-white" title="Excel"><i class="fa fa-file-excel"></i></button><button type="button" data-export="csv" class="h-8 w-8 rounded bg-blue-800 text-white" title="CSV"><i class="fa fa-file-csv"></i></button><button type="button" data-export="pdf" class="h-8 w-8 rounded bg-blue-800 text-white" title="PDF"><i class="fa fa-file-pdf"></i></button><button type="button" data-export="print" class="h-8 w-8 rounded bg-blue-800 text-white" title="Print"><i class="fa fa-print"></i></button><button type="button" data-column-toggle="curriculum-table" class="h-8 w-8 rounded bg-blue-800 text-white" title="Columns"><i class="fa fa-table-columns"></i></button><button type="button" data-modal-open="curriculum-form" class="rounded bg-blue-600 px-3 py-2 text-sm text-white"><i class="fa fa-plus"></i> Add</button></div></div>
        <div class="overflow-x-auto"><table id="curriculum-table" class="w-full text-left text-sm"><thead class="bg-blue-800 text-white"><tr>@if($kind==='term-settings')<th class="cursor-pointer px-3 py-2">Name</th><th class="cursor-pointer px-3 py-2">Start From</th><th class="cursor-pointer px-3 py-2">End</th><th class="cursor-pointer px-3 py-2">Status</th><th class="px-3 py-2">Action</th>@elseif($kind==='week-settings')<th class="cursor-pointer px-3 py-2">Name</th><th class="cursor-pointer px-3 py-2">Term</th><th class="cursor-pointer px-3 py-2">Start Date</th><th class="cursor-pointer px-3 py-2">End Date</th><th class="cursor-pointer px-3 py-2">Type</th><th class="px-3 py-2">Action</th>@else<th class="cursor-pointer px-3 py-2">Name</th><th class="cursor-pointer px-3 py-2">Term</th><th class="cursor-pointer px-3 py-2">Week</th><th class="cursor-pointer px-3 py-2">Date</th><th class="cursor-pointer px-3 py-2">Period</th><th class="cursor-pointer px-3 py-2">Status</th><th class="px-3 py-2">Action</th>@endif</tr></thead><tbody class="divide-y divide-neutral-200">
        @forelse($records as $r)
                @if($kind==='term-settings')<tr><td class="px-3 py-2">{{ $r->name }}</td><td class="px-3 py-2">{{ $r->start_date?->format('d M Y') ?? '—' }}</td><td class="px-3 py-2">{{ $r->end_date?->format('d M Y') ?? '—' }}</td><td class="px-3 py-2">{{ $r->is_active ? 'Active' : 'Non Active' }}</td><td class="px-3 py-2">@include('admin.academics.curriculum._actions',['routeBase'=>$routeBase,'record'=>$r])</td></tr>
            @elseif($kind==='week-settings')<tr><td class="px-3 py-2">{{ $r->name }}</td><td class="px-3 py-2">{{ $r->term?->name ?? '—' }}</td><td class="px-3 py-2">{{ $r->start_date?->format('d M Y') ?? '—' }}</td><td class="px-3 py-2">{{ $r->end_date?->format('d M Y') ?? '—' }}</td><td class="px-3 py-2">{{ $r->is_exam ? 'Exam' : ($r->is_holiday ? 'Holiday' : 'Teaching') }}</td><td class="px-3 py-2">@include('admin.academics.curriculum._actions',['routeBase'=>$routeBase,'record'=>$r])</td></tr>
            @else<tr><td class="px-3 py-2">{{ $r->name }}</td><td class="px-3 py-2">{{ $r->term?->name ?? '—' }}</td><td class="px-3 py-2">{{ $r->week?->name ?? '—' }}</td><td class="px-3 py-2">{{ $r->date?->format('d M Y') ?? '—' }}</td><td class="px-3 py-2">{{ $r->period ?? '—' }}</td><td class="px-3 py-2">{{ $r->is_working_day ? 'Working' : 'Off' }}</td><td class="px-3 py-2">@include('admin.academics.curriculum._actions',['routeBase'=>$routeBase,'record'=>$r])</td></tr>@endif
        @empty<tr><td colspan="7" class="px-3 py-8 text-center text-neutral-500">No data available</td></tr>@endforelse</tbody></table></div><div class="mt-3 flex items-center justify-between text-xs text-neutral-600"><span>Records: {{ $records->firstItem() ?? 0 }} to {{ $records->lastItem() ?? 0 }} of {{ $records->total() }}</span><span>{{ $records->links() }}</span></div>
    @else
        <div class="curriculum-toolbar curriculum-print-hide mb-3"><h2 class="text-lg font-medium">{{ $title }} List</h2><div class="curriculum-toolbar-controls"><form><input name="search" value="{{ request('search') }}" placeholder="Search..." class="rounded border border-neutral-300 px-3 py-2"></form><button type="button" data-export="copy" title="Copy" aria-label="Copy" class="h-8 w-8 rounded bg-blue-800 text-white hover:bg-blue-700"><i class="fa-regular fa-copy"></i></button><button type="button" data-export="excel" title="Excel" aria-label="Excel" class="h-8 w-8 rounded bg-blue-800 text-white hover:bg-blue-700"><i class="fa-regular fa-file-excel"></i></button><button type="button" data-export="csv" title="CSV" aria-label="CSV" class="h-8 w-8 rounded bg-blue-800 text-white hover:bg-blue-700"><i class="fa-solid fa-file-csv"></i></button><button type="button" data-export="pdf" title="PDF" aria-label="PDF" class="h-8 w-8 rounded bg-blue-800 text-white hover:bg-blue-700"><i class="fa-regular fa-file-pdf"></i></button><button type="button" data-export="print" title="Print" aria-label="Print" class="h-8 w-8 rounded bg-blue-800 text-white hover:bg-blue-700"><i class="fa-solid fa-print"></i></button><button type="button" data-column-toggle="curriculum-table" title="Columns" aria-label="Columns" class="h-8 w-8 rounded bg-blue-800 text-white hover:bg-blue-700"><i class="fa-solid fa-table-columns"></i></button><button type="button" data-modal-open="curriculum-form" class="rounded bg-blue-600 px-3 py-2 text-sm text-white hover:bg-blue-700"><i class="fa fa-plus"></i> Add</button></div></div>
        <div class="overflow-x-auto"><table id="curriculum-table" class="w-full text-left text-sm"><thead class="bg-blue-800 text-white"><tr>@if($kind==='subjects')<th class="cursor-pointer px-3 py-2">Subject ↕</th><th class="cursor-pointer px-3 py-2">Subject Code ↕</th><th class="cursor-pointer px-3 py-2">Subject Type ↕</th><th class="px-3 py-2">Action</th>@elseif($kind==='subject-groups')<th class="cursor-pointer px-3 py-2">Name ↕</th><th class="cursor-pointer px-3 py-2">Class ↕</th><th class="cursor-pointer px-3 py-2">Subject ↕</th><th class="px-3 py-2">Action</th>@elseif($kind==='chapters')<th class="cursor-pointer px-3 py-2">Class ↕</th><th class="px-3 py-2">Subject / Chapter</th>@elseif($kind==='topics')<th class="cursor-pointer px-3 py-2">Class ↕</th><th class="px-3 py-2">Subject / Chapter / Topic</th>@endif</tr></thead><tbody class="divide-y divide-neutral-200">
        @if(in_array($kind,['term-settings','week-settings','day-settings'],true))
            @forelse($records as $r)
                <tr><td class="px-3 py-2">{{ $r->name }}</td><td class="px-3 py-2">@include('admin.academics.curriculum._actions',['routeBase'=>$routeBase,'record'=>$r])</td></tr>
            @empty
                <tr><td colspan="2" class="px-3 py-8 text-center text-neutral-500">No data available</td></tr>
            @endforelse
        @else
        @forelse($records as $r)
            @if($kind==='subjects')<tr><td class="px-3 py-2">{{ $r->name }}</td><td class="px-3 py-2">{{ $r->code }}</td><td class="px-3 py-2">{{ ucfirst($r->type) }}</td><td class="px-3 py-2">@include('admin.academics.curriculum._actions',['routeBase'=>'subjects','record'=>$r])</td></tr>
            @elseif($kind==='subject-groups')<tr><td class="px-3 py-2">{{ $r->name }}</td><td class="px-3 py-2">{{ $classNames[$r->class_id]??$r->class_id }}</td><td class="px-3 py-2">@foreach($r->subjects as $s)<div>{{ $s->name }}</div>@endforeach</td><td class="px-3 py-2">@include('admin.academics.curriculum._actions',['routeBase'=>'subject-groups','record'=>$r])</td></tr>
            @elseif($kind==='chapters')<tr><td class="px-3 py-2">{{ $classNames[$r->class_id]??$r->class_id }}</td><td class="px-3 py-2"><div>{{ $r->subject?->name }}</div>{{ $r->name }}@if($r->urdu) / {{ $r->urdu }}@endif <span class="float-right">@include('admin.academics.curriculum._actions',['routeBase'=>'chapters','record'=>$r])</span></td></tr>
            @elseif($kind==='topics')<tr><td class="px-3 py-2">{{ $classNames[$r->class_id]??$r->class_id }}</td><td class="px-3 py-2"><div>{{ $r->chapter?->subject?->name }}</div><div>{{ $r->chapter?->name }}</div>{{ $r->name }}@if($r->urdu) / {{ $r->urdu }}@endif <span class="float-right">@include('admin.academics.curriculum._actions',['routeBase'=>'topics','record'=>$r])</span></td></tr>
            @endif
        @empty<tr><td colspan="4" class="px-3 py-8 text-center text-neutral-500">No data available</td></tr>@endforelse
        @endif
        </tbody></table></div><div class="mt-3 flex items-center justify-between text-xs text-neutral-600"><span>Records: {{ $records->firstItem() ?? 0 }} to {{ $records->lastItem() ?? 0 }} of {{ $records->total() }}</span><span>{{ $records->links() }}</span></div>
    </section>
    @endif
</div>
@push('scripts')<script>document.querySelectorAll('#curriculum-table th.cursor-pointer').forEach((h,i)=>h.addEventListener('click',()=>{const t=h.closest('table'),body=t.tBodies[0],rows=[...body.rows];const asc=h.dataset.asc!=='1';h.dataset.asc=asc?'1':'0';rows.sort((a,b)=>(a.cells[i]?.innerText||'').localeCompare(b.cells[i]?.innerText||'',undefined,{numeric:true,sensitivity:'base'})*(asc?1:-1));rows.forEach(r=>body.appendChild(r))}));document.querySelectorAll('[data-export]').forEach(b=>b.addEventListener('click',async e=>{e.preventDefault();const table=document.getElementById('curriculum-table'),rows=[...table.rows].map(r=>[...r.cells].filter((_,i)=>table.querySelectorAll('th')[i]?.style.display!=='none').map(c=>c.innerText.trim()).join('\t')).join('\n');if(b.dataset.export==='copy')await navigator.clipboard.writeText(rows);if(['csv','excel'].includes(b.dataset.export)){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows],{type:b.dataset.export==='csv'?'text/csv':'application/vnd.ms-excel'}));a.download='curriculum.'+(b.dataset.export==='csv'?'csv':'xls');a.click()}if(b.dataset.export==='pdf'||b.dataset.export==='print')window.print()}));document.getElementById('column-toggle')?.addEventListener('click',()=>{const table=document.getElementById('curriculum-table'),headers=[...table.tHead.rows[0].cells],hidden=headers.map(h=>h.style.display==='none'),menu=document.createElement('div');menu.className='absolute z-50 mt-2 rounded border border-neutral-200 bg-white p-2 text-sm text-neutral-800 shadow-lg';menu.innerHTML=headers.map((h,i)=>`<label class="block whitespace-nowrap px-2 py-1"><input type="checkbox" ${hidden[i]?'':'checked'} data-column="${i}"> ${h.innerText.replace(/[↕]/g,'')}</label>`).join('');const button=document.getElementById('column-toggle');button.parentElement.classList.add('relative');button.parentElement.appendChild(menu);menu.addEventListener('change',e=>{const i=Number(e.target.dataset.column);[...table.rows].forEach(r=>{if(r.cells[i])r.cells[i].style.display=e.target.checked?'':'none'});});menu.addEventListener('mouseleave',()=>menu.remove())});const add=document.getElementById('add-name');add?.addEventListener('click',()=>{const row=document.createElement('div');row.className='grid grid-cols-2 gap-2';row.innerHTML='<input name="eng_name[]" placeholder="Name English *" required class="rounded border border-neutral-300 px-3 py-2"><input name="urdu_name[]" placeholder="Name Urdu" class="rounded border border-neutral-300 px-3 py-2">';document.querySelector('#name-rows, #module-rows')?.appendChild(row)});document.getElementById('curriculum-class')?.addEventListener('change',e=>{const u=new URL(window.location);u.searchParams.set('class_id',e.target.value);u.searchParams.delete('subject_id');window.location=u});document.getElementById('curriculum-subject')?.addEventListener('change',e=>{const u=new URL(window.location);u.searchParams.set('subject_id',e.target.value);window.location=u});</script>@endpush
