<?php $__env->startSection('title', 'Merit List'); ?>
<?php $__env->startSection('content'); ?>
<?php $__env->startPush('styles'); ?>
<style>
.merit-toolbar{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:8px 12px;border-bottom:1px solid #d8dce5}.merit-search{width:220px;height:32px;border:1px solid #aeb8c6;border-radius:6px;padding:0 8px;font-size:12px;outline:0}.merit-tools{display:flex;gap:4px}.merit-tools button{width:30px;height:30px;border:0;border-radius:6px;background:#62676d;color:#fff;font-size:13px}.merit-table{width:100%;table-layout:fixed;border-collapse:collapse}.merit-table th{background:#626262!important;color:#fff!important;border:1px solid #858585;padding:8px 9px;font-size:11px;line-height:14px}.merit-table td{border:1px solid #bfc8d4;padding:6px 8px;font-size:11px;line-height:15px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.merit-table th:nth-child(1),.merit-table td:nth-child(1){width:9%}.merit-table th:nth-child(2),.merit-table td:nth-child(2){width:20%}.merit-table th:nth-child(3),.merit-table td:nth-child(3){width:19%}.merit-table th:nth-child(4),.merit-table td:nth-child(4){width:18%}.merit-table th:nth-child(5),.merit-table td:nth-child(5){width:17%}.merit-table th:nth-child(6),.merit-table td:nth-child(6){width:11%}.merit-table th:nth-child(7),.merit-table td:nth-child(7){width:10%}@media(max-width:700px){.merit-toolbar{align-items:flex-start;flex-direction:column}.merit-search{width:100%}.merit-tools{align-self:flex-end}}
</style>
<?php $__env->stopPush(); ?>
<section class="overflow-hidden rounded-md border border-[#d8dce5] bg-white shadow-sm"><div class="border-b border-[#d8dce5] px-4 py-3"><h2 class="text-[16px] font-medium">Merit List - Final Rankings</h2></div><div class="p-3"><div class="overflow-x-auto"><table class="min-w-full border border-[#ccd5e3] text-left text-[12px]"><thead class="bg-[#626262] text-white"><tr><th class="px-2 py-2">Rank</th><th class="px-2 py-2">Name</th><th class="px-2 py-2">Position</th><th class="px-2 py-2">Written Test</th><th class="px-2 py-2">Interview Score</th><th class="px-2 py-2">Total Score</th><th class="px-2 py-2">Percentage</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $candidates; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $candidate): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?> <?php $written=(int)($candidate->written_test_marks??0);$writtenTotal=(int)($candidate->written_test_total??100);$interview=(int)($candidate->interview_marks??0);$writtenPercentage=$writtenTotal>0?round(($written/$writtenTotal)*100,2):0;$interviewPercentage=round(($interview/100)*100,2);$possible=$writtenTotal+100;$percentage=$possible>0?round((($written+$interview)/$possible)*100,2):0; ?><tr class="border-t border-[#d8dce5]"><td class="px-2 py-2"><strong><?php echo e($loop->iteration); ?></strong><?php if($loop->iteration===1): ?><span class="medal gold">★</span><?php elseif($loop->iteration===2): ?><span class="medal silver">●</span><?php elseif($loop->iteration===3): ?><span class="medal bronze">●</span><?php endif; ?></td><td class="px-2 py-2"><strong><?php echo e($candidate->full_name); ?></strong></td><td class="px-2 py-2"><?php echo e($candidate->position_applied); ?></td><td class="px-2 py-2"><?php echo e($written); ?>/<?php echo e($writtenTotal); ?> <small>(<?php echo e($writtenPercentage); ?>%)</small></td><td class="px-2 py-2"><?php echo e($interview); ?>/100 <small>(<?php echo e($interviewPercentage); ?>%)</small></td><td class="px-2 py-2"><strong><?php echo e($written+$interview); ?></strong></td><td class="px-2 py-2"><span class="badge <?php echo e($percentage>=80?'good':($percentage>=60?'warn':'plain')); ?>"><?php echo e($percentage); ?>%</span></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7" class="px-2 py-4 text-center">No candidates found in merit list</td></tr><?php endif; ?></tbody></table></div></div></section>
<?php $__env->startPush('styles'); ?><style>.medal{display:inline-block;margin-left:7px;font-size:13px}.gold{color:#f0ad00}.silver{color:#777}.bronze{color:#c87932}.badge{display:inline-block;padding:4px 8px;border-radius:3px}.good{background:#d1e7dd;color:#146c43}.warn{background:#fff3cd;color:#997404}.plain{background:#e2e3e5;color:#41464b}small{color:#6b7280}</style><?php $__env->stopPush(); ?>
<?php $__env->startPush('scripts'); ?>
<script>
document.addEventListener('DOMContentLoaded',function(){const section=document.querySelector('section'),table=section?.querySelector('table');if(!section||!table)return;table.id='merit_table';table.classList.add('merit-table');const toolbar=document.createElement('div');toolbar.className='merit-toolbar';toolbar.innerHTML='<input id="merit_search" type="search" placeholder="Search..." class="merit-search"><div class="merit-tools"><button type="button" title="Copy"><i class="fa fa-copy"></i></button><button type="button" title="Excel"><i class="fa fa-file-excel-o"></i></button><button type="button" title="CSV"><i class="fa fa-file-text-o"></i></button><button type="button" title="PDF"><i class="fa fa-file-pdf-o"></i></button><button type="button" title="Print" onclick="window.print()"><i class="fa fa-print"></i></button><button type="button" title="Columns"><i class="fa fa-columns"></i></button></div>';table.parentElement.parentElement.insertBefore(toolbar,table.parentElement);document.getElementById('merit_search').addEventListener('input',function(){const term=this.value.toLowerCase().trim();table.querySelectorAll('tbody tr').forEach(row=>row.style.display=row.textContent.toLowerCase().includes(term)?'':'none')})});
</script>
<?php $__env->stopPush(); ?>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('admin.layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\TNT\cmslv_git_clone2\resources\views\admin\hrms\meritlist\index.blade.php ENDPATH**/ ?>