<?php $__env->startSection('title', $viewMode ? 'View Interview Rating' : ($rating ? 'Edit Interview Rating' : 'Interview Ratings')); ?>
<?php $editing=$rating&&!$viewMode; $v=fn($key,$fallback='')=>old($key,$rating?->{$key}??$fallback); $date=$rating?->interview_date?->format('Y-m-d')??old('interview_date',$today); ?>
<?php $__env->startSection('content'); ?>
<?php $__env->startPush('styles'); ?>
<style>
.grid.gap-3{display:grid;grid-template-columns:minmax(360px,1fr) minmax(0,2fr);align-items:start;gap:12px}
.grid.gap-3>section:last-child{min-width:0}.interview-rating-toolbar{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:8px 12px;border-bottom:1px solid #d8dce5}.interview-rating-search{width:220px;height:32px;border:1px solid #aeb8c6;border-radius:6px;padding:0 8px;font-size:12px;outline:0}.interview-rating-tools{display:flex;gap:4px}.interview-rating-tools button{width:30px;height:30px;border:0;border-radius:6px;background:#62676d;color:#fff;font-size:13px}.interview-rating-table{width:100%;table-layout:fixed;border-collapse:collapse}.interview-rating-table th{background:#626262!important;color:#fff!important;border:1px solid #858585;padding:7px 8px;font-size:11px;line-height:14px}.interview-rating-table td{border:1px solid #bfc8d4;padding:5px 7px;font-size:11px;line-height:15px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.interview-rating-table th:nth-child(1),.interview-rating-table td:nth-child(1){width:7%}.interview-rating-table th:nth-child(2),.interview-rating-table td:nth-child(2){width:22%}.interview-rating-table th:nth-child(3),.interview-rating-table td:nth-child(3){width:20%}.interview-rating-table th:nth-child(4),.interview-rating-table td:nth-child(4){width:15%}.interview-rating-table th:nth-child(5),.interview-rating-table td:nth-child(5){width:13%}.interview-rating-table th:nth-child(6),.interview-rating-table td:nth-child(6){width:13%}.interview-rating-table th:nth-child(7),.interview-rating-table td:nth-child(7){width:10%}.interview-rating-table td:last-child{overflow:visible;text-overflow:clip}.interview-rating-records .action{display:inline-flex;width:22px!important;height:22px!important;min-width:22px!important;align-items:center;justify-content:center;padding:0!important;margin:0 2px 0 0;border:0;font-size:10px;color:#fff}.interview-rating-records .action.view{background:#17a2b8}.interview-rating-records .action.edit{background:#264796}.interview-rating-records .action.delete{background:#dc3545}@media(max-width:900px){.grid.gap-3{grid-template-columns:1fr}.interview-rating-toolbar{align-items:flex-start;flex-direction:column}.interview-rating-search{width:100%}.interview-rating-tools{align-self:flex-end}}
</style>
<?php $__env->stopPush(); ?>
<div class="grid gap-3 xl:grid-cols-[minmax(320px,1fr)_minmax(520px,2fr)]"><section class="overflow-hidden rounded-md border border-[#d8dce5] bg-white shadow-sm"><div class="border-b border-[#d8dce5] px-4 py-3"><h2 class="text-[16px] font-medium"><?php echo e($viewMode?'View Interview Rating':($editing?'Edit Interview Rating':'Add Interview Rating')); ?></h2></div><form method="POST" action="<?php echo e($editing?route('admin.hrms.interviewratings.update',$rating->id,false):route('admin.hrms.interviewratings.store',absolute:false)); ?>" class="px-4 py-3"><?php echo csrf_field(); ?> <?php if($editing): ?> <?php echo method_field('PUT'); ?> <?php endif; ?> <?php if(session('success')): ?><div class="notice success"><?php echo e(session('success')); ?></div><?php endif; ?> <?php if($errors->any()): ?><div class="notice errorbox">Please correct the highlighted fields.</div><?php endif; ?>
<div class="mb-3"><label class="label">Candidate Name <span>*</span></label><?php if($viewMode): ?><input class="input" readonly value="<?php echo e($v('candidate_name')); ?>"><?php else: ?><select name="candidate_name" id="candidate_name" class="input" required><option value="">Select Candidate</option><?php $__currentLoopData = $candidates; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $candidate): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($candidate->full_name); ?>" data-position="<?php echo e($candidate->position_applied); ?>" data-salary="<?php echo e($candidate->min_salary_acceptable); ?>" <?php if($v('candidate_name')===$candidate->full_name): echo 'selected'; endif; ?>><?php echo e($candidate->full_name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select><?php endif; ?></div>
<div class="mb-3"><label class="label">Interview Date <span>*</span></label><input type="date" name="interview_date" value="<?php echo e($date); ?>" class="input" <?php echo e($viewMode?'readonly':'required'); ?>></div>
<div class="mb-3"><label class="label">Position Applied <span>*</span></label><input type="text" name="position_applied" value="<?php echo e($v('position_applied')); ?>" class="input" <?php echo e($viewMode?'readonly':'required'); ?>></div>
<div class="mb-3"><label class="label">Salary Expectation</label><input type="text" name="salary_expectation" value="<?php echo e($v('salary_expectation')); ?>" class="input" <?php echo e($viewMode?'readonly':''); ?>></div>
<?php $__currentLoopData = $ratingFields; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $field): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?> <?php $labels=['appearance_rating'=>'Appearance Rating (1-10)','communication_rating'=>'Communication Rating (1-10)','reasoning_rating'=>'Reasoning Rating (1-10)','education_rating'=>'Education Rating (1-10)','job_knowledge_rating'=>'Job Knowledge Rating (1-10)','work_experience_rating'=>'Work Experience Rating (1-10)','general_knowledge_rating'=>'General Knowledge Rating (1-10)','iq_level_rating'=>'IQ Level Rating (1-10)','pose_maturity_rating'=>'Pose Maturity Rating (1-10)','personality_rating'=>'Personality Rating (1-10)']; ?><div class="mb-3"><label class="label"><?php echo e($labels[$field]); ?></label><input type="number" min="0" max="10" name="<?php echo e($field); ?>" value="<?php echo e($v($field)); ?>" class="input" <?php echo e($viewMode?'readonly':''); ?>></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
<div class="mb-3"><label class="label">Final Decision</label><?php if($viewMode): ?><input class="input" readonly value="<?php echo e($v('final_decision')); ?>"><?php else: ?><select name="final_decision" class="input"><option value="pending" <?php if($v('final_decision','pending')==='pending'): echo 'selected'; endif; ?>>Pending</option><option value="recommended" <?php if($v('final_decision')==='recommended'): echo 'selected'; endif; ?>>Recommended</option><option value="not_recommended" <?php if($v('final_decision')==='not_recommended'): echo 'selected'; endif; ?>>Not Recommended</option></select><?php endif; ?></div>
<?php if(!$viewMode): ?><div class="flex justify-end gap-2 pt-2"><a class="button secondary" href="<?php echo e(route('admin.hrms.interviewratings.index',absolute:false)); ?>"><?php echo e($editing?'Cancel':'Reset'); ?></a><button class="button primary"><?php echo e($editing?'Update':'Save'); ?></button></div><?php else: ?><div class="flex justify-end gap-2 pt-2"><a class="button secondary" href="<?php echo e(route('admin.hrms.interviewratings.index',absolute:false)); ?>">Back to List</a><a class="button primary" href="<?php echo e(route('admin.hrms.interviewratings.edit',$rating->id,false)); ?>">Edit</a></div><?php endif; ?></form></section>
<section class="overflow-hidden rounded-md border border-[#d8dce5] bg-white shadow-sm"><div class="border-b border-[#d8dce5] px-4 py-3"><h2 class="text-[16px] font-medium">Interview Ratings List</h2></div><div class="overflow-x-auto p-3"><table class="min-w-full border border-[#ccd5e3] text-left text-[12px]"><thead class="bg-[#626262] text-white"><tr><th class="px-2 py-2">ID</th><th class="px-2 py-2">Candidate</th><th class="px-2 py-2">Position</th><th class="px-2 py-2">Interview Date</th><th class="px-2 py-2">Total Points</th><th class="px-2 py-2">Decision</th><th class="px-2 py-2">Action</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $ratings; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr class="border-t border-[#d8dce5]"><td class="px-2 py-2"><?php echo e($item->id); ?></td><td class="px-2 py-2"><?php echo e($item->candidate_name); ?></td><td class="px-2 py-2"><?php echo e($item->position_applied); ?></td><td class="px-2 py-2"><?php echo e($item->interview_date?->format('Y-m-d')); ?></td><td class="px-2 py-2"><?php echo e($item->total_points??0); ?></td><td class="px-2 py-2"><select class="decision-select input" data-id="<?php echo e($item->id); ?>"><option value="pending" <?php if($item->final_decision==='pending'): echo 'selected'; endif; ?>>Pending</option><option value="recommended" <?php if($item->final_decision==='recommended'): echo 'selected'; endif; ?>>Recommended</option><option value="not_recommended" <?php if($item->final_decision==='not_recommended'): echo 'selected'; endif; ?>>Not Recommended</option></select></td><td class="whitespace-nowrap px-2 py-2"><a class="action view" href="<?php echo e(route('admin.hrms.interviewratings.show',$item->id,false)); ?>">●</a><a class="action edit" href="<?php echo e(route('admin.hrms.interviewratings.edit',$item->id,false)); ?>">✎</a><form class="inline" method="POST" action="<?php echo e(route('admin.hrms.interviewratings.destroy',$item->id,false)); ?>" onsubmit="return confirm('Are you sure you want to delete this interview rating?')"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="action delete">×</button></form></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7" class="px-2 py-4 text-center">No interview ratings found</td></tr><?php endif; ?></tbody></table></div></section></div>
<?php $__env->startPush('styles'); ?><style>.label{display:block;margin-bottom:5px;font-size:13px;font-weight:600;color:#222}.label span{color:#e11d48}.input{width:100%;border:1px solid #cfd6e0;padding:7px 10px;font-size:13px;color:#333;outline:0}.notice{margin-bottom:12px;padding:8px;font-size:12px}.success{background:#f0fdf4;color:#15803d}.errorbox{background:#fef2f2;color:#b91c1c}.button{display:inline-block;padding:7px 14px;font-size:12px;font-weight:600}.primary{border:0;background:#264796;color:#fff}.secondary{border:1px solid #cfd6e0;color:#333}.action{display:inline-flex;width:24px;height:24px;align-items:center;justify-content:center;margin-right:3px;color:#fff;text-decoration:none;border:0}.view{background:#17a2b8}.edit{background:#264796}.delete{background:#dc3545;cursor:pointer}.decision-select{width:125px;padding:5px 6px}</style><?php $__env->stopPush(); ?>
<?php $__env->startPush('scripts'); ?><script>document.addEventListener('DOMContentLoaded',()=>{const candidate=document.getElementById('candidate_name');if(candidate)candidate.addEventListener('change',()=>{const o=candidate.options[candidate.selectedIndex],p=document.querySelector('[name=position_applied]'),s=document.querySelector('[name=salary_expectation]');if(o.dataset.position)p.value=o.dataset.position;if(o.dataset.salary){const n=parseFloat(o.dataset.salary);s.value=Number.isNaN(n)?o.dataset.salary:'Rs. '+n.toFixed(0)+'.00'}});document.querySelectorAll('.decision-select').forEach(select=>select.addEventListener('change',()=>{const old=select.dataset.old||select.value;fetch(<?php echo json_encode(url('/admin/hrms/interviewratings'), 15, 512) ?>.replace(/\/$/,'')+'/'+select.dataset.id+'/decision',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content,'Accept':'application/json'},body:JSON.stringify({decision:select.value})}).then(r=>r.json()).then(d=>{if(!d.success)select.value=old;else select.dataset.old=select.value}).catch(()=>select.value=old)}))})</script><?php $__env->stopPush(); ?>
<?php $__env->startPush('scripts'); ?>
<script>
document.addEventListener('DOMContentLoaded',function(){
    const records=document.querySelector('.grid.gap-3>section:last-child'),table=records?.querySelector('table');
    if(!records||!table)return;
    records.classList.add('interview-rating-records');table.id='interview_rating_table';table.classList.add('interview-rating-table');
    const toolbar=document.createElement('div');toolbar.className='interview-rating-toolbar';toolbar.innerHTML='<input id="interview_rating_search" type="search" placeholder="Search..." class="interview-rating-search"><div class="interview-rating-tools"><button type="button" title="Copy"><i class="fa fa-copy"></i></button><button type="button" title="Excel"><i class="fa fa-file-excel-o"></i></button><button type="button" title="CSV"><i class="fa fa-file-text-o"></i></button><button type="button" title="PDF"><i class="fa fa-file-pdf-o"></i></button><button type="button" title="Print" onclick="window.print()"><i class="fa fa-print"></i></button><button type="button" title="Columns"><i class="fa fa-columns"></i></button></div>';table.parentElement.insertBefore(toolbar,table);
    table.querySelectorAll('.action.view').forEach(x=>x.innerHTML='<i class="fa fa-eye"></i>');table.querySelectorAll('.action.edit').forEach(x=>x.innerHTML='<i class="fa fa-pencil"></i>');table.querySelectorAll('.action.delete').forEach(x=>x.innerHTML='<i class="fa fa-times"></i>');
    document.getElementById('interview_rating_search').addEventListener('input',function(){const term=this.value.toLowerCase().trim();table.querySelectorAll('tbody tr').forEach(row=>row.style.display=row.textContent.toLowerCase().includes(term)?'':'none')});
});
</script>
<?php $__env->stopPush(); ?>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('admin.layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\TNT\cmslv_git_clone2\resources\views\admin\hrms\interviewratings\index.blade.php ENDPATH**/ ?>