@extends('admin.layouts.app')
@section('title', $viewMode ? 'View Job Application' : ($application ? 'Edit Job Application' : 'Job Applications'))
@php
 $editing=$application&&!$viewMode; $v=fn($key,$fallback='')=>old($key,$application?->{$key}??$fallback); $dob=$application?->date_of_birth?->format('Y-m-d')??old('date_of_birth','');
 $qualifications=old('qualifications',$application?->qualifications??[]); $previousJobs=old('previous_jobs',$application?->previous_jobs??[]); $experiences=old('recent_experience',$application?->recent_experience??[]);
@endphp
@section('content')
<div class="job-app-layout items-start gap-3">
<section class="overflow-hidden rounded-md border border-[#d8dce5] bg-white shadow-sm"><div class="border-b border-[#d8dce5] px-4 py-3"><h2 class="text-[16px] font-medium">{{ $viewMode?'View Job Application':($editing?'Edit Job Application':'Add Job Application') }}</h2></div>
<form method="POST" enctype="multipart/form-data" action="{{ $editing?route('admin.hrms.jobapplications.update',$application->id,false):route('admin.hrms.jobapplications.store',absolute:false) }}" class="px-4 py-3">@csrf @if($editing) @method('PUT') @endif
@if(session('success'))<div class="notice success">{{session('success')}}</div>@endif @if($errors->any())<div class="notice errorbox">Please correct the highlighted fields.</div>@endif
@foreach([['full_name','Full Name',true],['father_husband_name','Father/Husband Name',true],['cnic','CNIC',true],['min_salary_acceptable','Min Salary Acceptable',true],['nationality','Nationality',true],['place_of_birth','Place of Birth',true],['contact_numbers','Contact Numbers',true]] as [$name,$label,$required])<div class="mb-3"><label class="label">{{$label}} @if($required)<span>*</span>@endif</label><input type="text" name="{{$name}}" value="{{ $v($name,$name==='nationality'?'Pakistani':'') }}" class="input" @if($name==='cnic') placeholder="12345-1234567-1" maxlength="15" pattern="[0-9]{5}-[0-9]{7}-[0-9]{1}" oninput="formatCNIC(this)" @elseif($name==='contact_numbers') placeholder="0300-1234567" maxlength="12" pattern="[0-9]{4}-[0-9]{7}" oninput="formatPhone(this)" @endif {{ $viewMode?'readonly':($required?'required':'') }}></div>@endforeach
<div class="mb-3"><label class="label">Position Applied <span>*</span></label>@if($viewMode)<input class="input" readonly value="{{$v('position_applied')}}">@else<select name="position_applied" id="position_applied" class="input" required><option value="">Select Position</option>@foreach($jobTitles as $title)<option value="{{$title}}" @selected($v('position_applied')===$title)>{{$title}}</option>@endforeach</select>@endif</div>
@foreach([['religion','Religion',$religions],['gender','Gender',$genders],['marital_status','Marital Status',$maritalStatuses]] as [$name,$label,$options])<div class="mb-3"><label class="label">{{$label}} <span>*</span></label>@if($viewMode)<input class="input" readonly value="{{$v($name)}}">@else<select name="{{$name}}" class="input" required><option value="">Select {{$label}}</option>@foreach($options as $option)<option value="{{$option}}" @selected($v($name)===$option)>{{$option}}</option>@endforeach</select>@endif</div>@endforeach
<div class="mb-3"><label class="label">Gender/Physical Details</label><div class="grid grid-cols-3 gap-2"><input type="number" name="height_ft" value="{{$v('height_ft')}}" class="input" placeholder="Height Ft" {{ $viewMode?'readonly':'' }}><input type="number" name="height_inches" value="{{$v('height_inches')}}" class="input" placeholder="Height Inches" {{ $viewMode?'readonly':'' }}><input type="number" name="weight_kg" value="{{$v('weight_kg')}}" class="input" placeholder="Weight Kg" {{ $viewMode?'readonly':'' }}></div></div>
<div class="mb-3"><label class="label">Date of Birth <span>*</span></label><input type="date" name="date_of_birth" value="{{$dob}}" class="input" {{ $viewMode?'readonly':'required' }}></div>
<div class="mb-3"><label class="label">Mailing Address <span>*</span></label><textarea name="mailing_address" rows="3" class="input" {{ $viewMode?'readonly':'required' }}>{{$v('mailing_address')}}</textarea></div>
<div class="mb-3"><label class="label">Photograph</label>@if(!$viewMode)<input type="file" name="photograph" accept="image/*" class="input">@endif @if($application?->photograph)<img class="mt-2 h-24 w-24 object-cover" src="{{asset('uploads/job_photos/'.$application->photograph)}}">@endif</div>
<div class="panel"><div class="panel-head"><b>QUALIFICATION</b>@if(!$viewMode)<button type="button" class="button add" onclick="addQualification()">+ Add Qualification</button>@endif</div><div class="overflow-x-auto"><table class="dynamic-table"><thead><tr><th>Sr.#</th><th>Level</th><th>Subjects</th><th>Institute</th><th>Session</th><th>Grade/Division</th><th>Marks in %</th><th>Office Use</th><th></th></tr></thead><tbody id="qualificationTableBody"></tbody></table></div></div>
<div class="panel"><div class="panel-head"><b>Previous Jobs</b>@if(!$viewMode)<button type="button" class="button add" onclick="addPreviousJob()">+ Add Job</button>@endif</div><div class="overflow-x-auto"><table class="dynamic-table"><thead><tr><th>Sr.#</th><th>Organization</th><th>Designation</th><th>Duration</th><th>Major Responsibilities</th><th></th></tr></thead><tbody id="previousJobsTableBody"></tbody></table></div></div>
<div class="panel"><div class="panel-head"><b>EXPERIENCE (Most Recent)</b>@if(!$viewMode)<button type="button" class="button add" onclick="addExperience()">+ Add Experience</button>@endif</div><div id="experienceContainer" class="p-2"></div></div>
@if(!$viewMode)<div class="flex justify-end gap-2 pt-3"><a class="button secondary" href="{{route('admin.hrms.jobapplications.index',absolute:false)}}">{{$editing?'Cancel':'Reset'}}</a><button class="button primary">{{$editing?'Update':'Save'}}</button></div>@else<div class="flex justify-end gap-2 pt-3"><a class="button secondary" href="{{route('admin.hrms.jobapplications.index',absolute:false)}}">Back to List</a><a class="button primary" href="{{route('admin.hrms.jobapplications.edit',$application->id,false)}}">Edit</a></div>@endif
</form></section>
<section class="job-app-records overflow-hidden rounded-md border border-[#d8dce5] bg-white shadow-sm"><div class="border-b border-[#d8dce5] px-4 py-3"><h2 class="text-[16px] font-medium">Job Applications List</h2></div><div class="job-app-toolbar"><input id="job_app_search" type="search" placeholder="Search..." class="job-app-search"><div class="job-app-tools"><button type="button" title="Copy"><i class="fa fa-copy"></i></button><button type="button" title="Excel"><i class="fa fa-file-excel-o"></i></button><button type="button" title="CSV"><i class="fa fa-file-text-o"></i></button><button type="button" title="PDF"><i class="fa fa-file-pdf-o"></i></button><button type="button" title="Print" onclick="window.print()"><i class="fa fa-print"></i></button><button type="button" title="Columns"><i class="fa fa-columns"></i></button></div></div><div class="overflow-x-auto p-3"><table id="job_app_table" class="job-app-table min-w-full border-collapse text-left text-[11px]"><thead><tr><th>ID <i class="fa fa-caret-down"></i></th><th>Name <i class="fa fa-caret-down"></i></th><th>Position <i class="fa fa-caret-down"></i></th><th>CNIC <i class="fa fa-caret-down"></i></th><th>Status</th><th>Date <i class="fa fa-caret-down"></i></th><th>Action</th></tr></thead><tbody>@forelse($applications as $item)<tr class="job-app-row"><td>{{$loop->count-$loop->iteration+1}}</td><td title="Father/Husband: {{$item->father_husband_name}} | Contact: {{$item->contact_numbers}} | Religion: {{$item->religion}}">{{$item->full_name}}</td><td>{{$item->position_applied}}</td><td>{{$item->cnic}}</td><td><select class="status-select input" data-id="{{$item->id}}"><option @selected($item->status==='Pending')>Pending</option><option @selected($item->status==='Approved')>Approved</option><option @selected($item->status==='Rejected')>Rejected</option></select></td><td>{{$item->created_at?->format('Y-m-d')}}</td><td class="job-app-action"><a class="action view" title="View" href="{{route('admin.hrms.jobapplications.show',$item->id,false)}}"><i class="fa fa-eye"></i></a><a class="action print" title="Print" target="_blank" href="{{route('admin.hrms.jobapplications.print',$item->id,false)}}"><i class="fa fa-print"></i></a><a class="action edit" title="Edit" href="{{route('admin.hrms.jobapplications.edit',$item->id,false)}}"><i class="fa fa-pencil"></i></a><form class="inline" method="POST" action="{{route('admin.hrms.jobapplications.destroy',$item->id,false)}}" onsubmit="return confirm('Are you sure you want to delete this job application?')">@csrf @method('DELETE')<button class="action delete" title="Delete"><i class="fa fa-times"></i></button></form></td></tr>@empty<tr><td colspan="7">No job applications found</td></tr>@endforelse</tbody></table><div class="job-app-count">Records: {{$applications->count() ? 1 : 0}} to {{$applications->count()}} of {{$applications->count()}}</div></div></section>
</div>
@push('scripts')<script>
const readonly=@json($viewMode), degrees=@json($degreeLevels), oldQualifications=@json($qualifications), oldJobs=@json($previousJobs), oldExperiences=@json($experiences);let qi=0,ji=0,ei=0;
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function addQualification(data={},idx=qi){const b=document.getElementById('qualificationTableBody'),r=document.createElement('tr');r.id='q-'+idx;let opts='<option value="">-- Select Level --</option>'+degrees.map(x=>`<option ${data.level===x?'selected':''}>${x}</option>`).join('');r.innerHTML=`<td>${idx+1}</td><td><select name="qualifications[${idx}][level]" ${readonly?'disabled':''}>${opts}</select></td><td><input name="qualifications[${idx}][subjects]" value="${esc(data.subjects)}" ${readonly?'readonly':''}></td><td><input name="qualifications[${idx}][institute]" value="${esc(data.institute)}" ${readonly?'readonly':''}></td><td><input name="qualifications[${idx}][session]" value="${esc(data.session)}" ${readonly?'readonly':''}></td><td><input name="qualifications[${idx}][grade]" value="${esc(data.grade)}" ${readonly?'readonly':''}></td><td><input type="number" name="qualifications[${idx}][marks]" value="${esc(data.marks)}" ${readonly?'readonly':''}></td><td><input name="qualifications[${idx}][office_use]" value="${esc(data.office_use)}" ${readonly?'readonly':''}></td><td>${readonly?'':'<button type="button" class="action delete" onclick="document.getElementById(\'q-'+idx+'\').remove()">×</button>'}</td>`;b.appendChild(r);qi=Math.max(qi,idx+1)}
function addPreviousJob(data={},idx=ji){const b=document.getElementById('previousJobsTableBody'),r=document.createElement('tr');r.id='j-'+idx;r.innerHTML=`<td>${idx+1}</td><td><input name="previous_jobs[${idx}][organization]" value="${esc(data.organization)}" ${readonly?'readonly':''}></td><td><input name="previous_jobs[${idx}][designation]" value="${esc(data.designation)}" ${readonly?'readonly':''}></td><td><input name="previous_jobs[${idx}][duration]" value="${esc(data.duration)}" ${readonly?'readonly':''}></td><td><textarea name="previous_jobs[${idx}][responsibilities]" ${readonly?'readonly':''}>${esc(data.responsibilities)}</textarea></td><td>${readonly?'':'<button type="button" class="action delete" onclick="document.getElementById(\'j-'+idx+'\').remove()">×</button>'}</td>`;b.appendChild(r);ji=Math.max(ji,idx+1)}
function addExperience(data={},idx=ei){const b=document.getElementById('experienceContainer'),d=document.createElement('div');d.className='experience-entry';d.id='e-'+idx;const f=(key,label)=>`<div><label>${label}</label><input name="recent_experience[${idx}][${key}]" value="${esc(data[key])}" ${readonly?'readonly':''}></div>`;d.innerHTML=`<div class="panel-head"><b>Experience Entry #${idx+1}</b>${readonly?'':'<button type="button" class="button delete" onclick="document.getElementById(\'e-'+idx+'\').remove()">Delete</button>'}</div><div class="experience-grid">${f('company','School/Organization/Company')}${f('address','Address')}${f('phone','Phone No.')}${f('joined_as','Joined As')}${f('left_as','Left As')}${f('reason_to_leave','Reason To Leave')}${f('salary','Salary')}${f('reporting_to','Reporting to')}</div>`;b.appendChild(d);ei=Math.max(ei,idx+1)}
function formatCNIC(i){let v=i.value.replace(/\D/g,'').slice(0,13);if(v.length>5)v=v.slice(0,5)+'-'+v.slice(5);if(v.length>13)v=v.slice(0,13)+'-'+v.slice(13);i.value=v}function formatPhone(i){let v=i.value.replace(/\D/g,'').slice(0,11);if(v.length>4)v=v.slice(0,4)+'-'+v.slice(4);i.value=v}
document.addEventListener('DOMContentLoaded',()=>{oldQualifications.forEach((x,i)=>addQualification(x,i));oldJobs.forEach((x,i)=>addPreviousJob(x,i));oldExperiences.forEach((x,i)=>addExperience(x,i));if(!readonly){if(!oldQualifications.length)addQualification();if(!oldJobs.length)addPreviousJob();if(!oldExperiences.length)addExperience()}const p=document.getElementById('position_applied');if(p)p.addEventListener('change',()=>fetch(@json(route('admin.hrms.jobapplications.job-details',absolute:false)),{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content,'Accept':'application/json'},body:JSON.stringify({position:p.value})}).then(r=>r.json()).then(d=>document.querySelector('[name=min_salary_acceptable]').value=d.salary||''));document.querySelectorAll('.status-select').forEach(s=>s.addEventListener('change',()=>fetch(@json(url('/admin/hrms/jobapplications')).replace(/\/$/,'')+'/'+s.dataset.id+'/status',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content,'Accept':'application/json'},body:JSON.stringify({status:s.value})}).then(r=>r.json()).then(d=>{if(!d.success)alert('Failed to update status')})))})
</script>@endpush
@push('scripts')
<script>document.addEventListener('DOMContentLoaded',function(){const search=document.getElementById('job_app_search');if(!search)return;search.addEventListener('input',function(){const term=this.value.toLowerCase().trim();document.querySelectorAll('#job_app_table .job-app-row').forEach(function(row){row.style.display=row.textContent.toLowerCase().includes(term)?'':'none'})})});</script>
@endpush
@endsection
