<?php
namespace App\Http\Controllers\Admin\Hrms;
use App\Http\Controllers\Controller; use App\Models\Hrms\Staff; use App\Models\Hrms\TrainingAgenda; use Illuminate\Http\Request; use Illuminate\Http\RedirectResponse; use Illuminate\View\View;
class TrainingAgendaController extends Controller {
    public function index(Request $request): View { return view('admin.hrms.training.agenda', $this->data($request)); }
    public function store(Request $request): RedirectResponse { $data=$request->validate(['prepared_by'=>'required|string|max:255','topic'=>'array','topic.*'=>'nullable|string|max:255','resource_person'=>'array','resource_person.*'=>'nullable|string|max:255','venue'=>'array','venue.*'=>'nullable|string|max:255','timing_date'=>'array','timing_date.*'=>'nullable|date','timing_time'=>'array','timing_time.*'=>'nullable','audience'=>'array','audience.*'=>'nullable|string|max:255','required_material'=>'array','required_material.*'=>'nullable|string|max:255']); TrainingAgenda::create(['prepared_by'=>$data['prepared_by'],'agenda_items'=>$this->items($data)]); return to_route('admin.hrms.training.agenda.index')->with('success','Training Agenda created successfully.'); }
    public function edit(TrainingAgenda $trainingAgenda, Request $request): View { return view('admin.hrms.training.agenda', $this->data($request,$trainingAgenda)); }
    public function update(Request $request, TrainingAgenda $trainingAgenda): RedirectResponse { $data=$request->validate(['prepared_by'=>'required|string|max:255','topic'=>'array','topic.*'=>'nullable|string|max:255','resource_person'=>'array','resource_person.*'=>'nullable|string|max:255','venue'=>'array','venue.*'=>'nullable|string|max:255','timing_date'=>'array','timing_date.*'=>'nullable|date','timing_time'=>'array','timing_time.*'=>'nullable','audience'=>'array','audience.*'=>'nullable|string|max:255','required_material'=>'array','required_material.*'=>'nullable|string|max:255']); $trainingAgenda->update(['prepared_by'=>$data['prepared_by'],'agenda_items'=>$this->items($data)]); return to_route('admin.hrms.training.agenda.index')->with('success','Training Agenda updated successfully.'); }
    public function show(TrainingAgenda $trainingAgenda, Request $request): View { return view('admin.hrms.training.agenda', $this->data($request,$trainingAgenda,true)); }
    public function destroy(TrainingAgenda $trainingAgenda): RedirectResponse { $trainingAgenda->delete(); return back()->with('success','Training Agenda deleted successfully.'); }
    private function items(array $data): array { $items=[]; foreach(($data['topic']??[]) as $i=>$topic) if(trim((string)$topic)!=='') $items[]=['topic'=>$topic,'resource_person'=>$data['resource_person'][$i]??'','venue'=>$data['venue'][$i]??'','timing_date'=>$data['timing_date'][$i]??'','timing_time'=>$data['timing_time'][$i]??'','audience'=>$data['audience'][$i]??'','required_material'=>$data['required_material'][$i]??'']; return $items; }
    private function data(Request $request, ?TrainingAgenda $agenda=null, bool $view=false): array { return ['agendas'=>TrainingAgenda::latest()->get(),'agenda'=>$agenda,'viewMode'=>$view,'staff'=>$this->staff($request),'selectedStaff'=>$agenda?->prepared_by,'today'=>now()->toDateString()]; }
    private function staff(Request $request) { return Staff::query()->where('is_active',1)->when($request->integer('brc_id'),fn($q)=>$q->where('brc_id',$request->integer('brc_id')))->orderBy('name')->orderBy('surname')->get(['id','name','surname']); }
}
