@extends('admin.layouts.app')
@section('title', $viewMode ? 'View Staff Recruitment Order' : ($order ? 'Edit Staff Recruitment Order' : 'Staff Recruitment Orders'))
@php $editing=$order&&!$viewMode; $v=fn($key,$fallback='')=>old($key,$order?->{$key}??$fallback); $date=$order?->order_date?->format('Y-m-d')??old('order_date',$today); @endphp
@section('content')
<div class="grid gap-3 xl:grid-cols-[minmax(320px,1fr)_minmax(560px,2fr)]"><section class="overflow-hidden rounded-md border border-[#d8dce5] bg-white shadow-sm"><div class="border-b border-[#d8dce5] px-4 py-3"><h2 class="text-[16px] font-medium">{{ $viewMode?'View Staff Recruitment Order':($editing?'Edit Staff Recruitment Order':'Add Staff Recruitment Order') }}</h2></div><form method="POST" action="{{ $editing?route('admin.hrms.staffrecruitmentorders.update',$order->id,false):route('admin.hrms.staffrecruitmentorders.store',absolute:false) }}" class="px-4 py-3">@csrf @if($editing) @method('PUT') @endif @if(session('success'))<div class="notice success">{{session('success')}}</div>@endif @if($errors->any())<div class="notice errorbox">Please correct the highlighted fields.</div>@endif
<div class="mb-3"><label class="label">Employee Name <span>*</span></label>@if($viewMode)<input class="input" readonly value="{{$v('employee_name')}}">@else<select name="employee_name" id="employee_name" class="input" required><option value="">Select from Job Offers</option>@foreach($offers as $offerOption)<option value="{{$offerOption->candidate_name}}" data-position="{{$offerOption->position}}" data-cnic="{{$offerOption->cnic??''}}" data-phone="{{$offerOption->contact_numbers??''}}" @selected($v('employee_name')===$offerOption->candidate_name)>{{$offerOption->candidate_name}} - {{$offerOption->position}}</option>@endforeach</select>@endif</div>
<div class="mb-3"><label class="label">Position <span>*</span></label><input type="text" name="position" id="position" value="{{$v('position')}}" class="input" readonly></div><div class="mb-3"><label class="label">Order Date <span>*</span></label><input type="date" name="order_date" value="{{$date}}" class="input" {{ $viewMode?'readonly':'required' }}></div><div class="mb-3"><label class="label">Department <span>*</span></label><input type="text" name="department" value="{{$v('department')}}" class="input" {{ $viewMode?'readonly':'required' }}></div><div class="mb-3"><label class="label">Designation <span>*</span></label><input type="text" name="designation" id="designation" value="{{$v('designation')}}" class="input" {{ $viewMode?'readonly':'required' }}></div><div class="mb-3"><label class="label">Employee CNIC</label><input type="text" name="employee_cnic" id="employee_cnic" value="{{$v('employee_cnic')}}" class="input" readonly></div><div class="mb-3"><label class="label">Personal Phone</label><input type="text" name="personal_phone" id="personal_phone" value="{{$v('personal_phone')}}" class="input" readonly></div>
@if(!$viewMode)<div class="flex justify-end gap-2 pt-2"><a class="button secondary" href="{{route('admin.hrms.staffrecruitmentorders.index',absolute:false)}}">{{$editing?'Cancel':'Reset'}}</a><button class="button primary">{{$editing?'Update':'Save'}}</button></div>@else<div class="flex justify-end gap-2 pt-2"><a class="button secondary" href="{{route('admin.hrms.staffrecruitmentorders.index',absolute:false)}}">Back to List</a><a class="button primary" href="{{route('admin.hrms.staffrecruitmentorders.edit',$order->id,false)}}">Edit</a></div>@endif</form></section>
<section class="overflow-hidden rounded-md border border-[#d8dce5] bg-white shadow-sm"><div class="border-b border-[#d8dce5] px-4 py-3"><h2 class="text-[16px] font-medium">Staff Recruitment Orders List</h2></div><div class="overflow-x-auto p-3"><table class="min-w-full border border-[#ccd5e3] text-left text-[12px]"><thead class="bg-[#626262] text-white"><tr><th class="px-2 py-2">ID</th><th class="px-2 py-2">Employee Name</th><th class="px-2 py-2">Position</th><th class="px-2 py-2">Department</th><th class="px-2 py-2">Designation</th><th class="px-2 py-2">CNIC</th><th class="px-2 py-2">Phone</th><th class="px-2 py-2">Order Date</th><th class="px-2 py-2">Action</th></tr></thead><tbody>@forelse($orders as $item)<tr class="border-t border-[#d8dce5]"><td class="px-2 py-2">{{$item->id}}</td><td class="px-2 py-2"><strong>{{$item->employee_name}}</strong></td><td class="px-2 py-2">{{$item->position}}</td><td class="px-2 py-2">{{$item->department}}</td><td class="px-2 py-2">{{$item->designation}}</td><td class="px-2 py-2">{{$item->employee_cnic}}</td><td class="px-2 py-2">{{$item->personal_phone}}</td><td class="px-2 py-2">{{$item->order_date?->format('Y-m-d')}}</td><td class="whitespace-nowrap px-2 py-2"><a class="action view" href="{{route('admin.hrms.staffrecruitmentorders.show',$item->id,false)}}">●</a><a class="action edit" href="{{route('admin.hrms.staffrecruitmentorders.edit',$item->id,false)}}">✎</a><form class="inline" method="POST" action="{{route('admin.hrms.staffrecruitmentorders.destroy',$item->id,false)}}" onsubmit="return confirm('Are you sure you want to delete this recruitment order?')">@csrf @method('DELETE')<button class="action delete">×</button></form></td></tr>@empty<tr><td colspan="9" class="px-2 py-4 text-center">No staff recruitment orders found</td></tr>@endforelse</tbody></table></div></section></div>
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const s=document.getElementById('employee_name');if(!s)return;const fill=()=>{const o=s.options[s.selectedIndex],set=(id,key)=>{const e=document.getElementById(id);if(e)e.value=o.dataset[key]||''};set('position','position');set('employee_cnic','cnic');set('personal_phone','phone')};s.addEventListener('change',fill);if(s.value)fill()})</script>@endpush
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',function(){const records=document.querySelector('.grid.gap-3>section:last-child'),table=records?.querySelector('table');if(!records||!table)return;records.classList.add('recruitment-order-records');table.id='recruitment_order_table';table.classList.add('recruitment-order-table');const toolbar=document.createElement('div');toolbar.className='recruitment-order-toolbar';toolbar.innerHTML='<input id="recruitment_order_search" type="search" placeholder="Search..." class="recruitment-order-search"><div class="recruitment-order-tools"><button type="button" title="Copy"><i class="fa fa-copy"></i></button><button type="button" title="Excel"><i class="fa fa-file-excel-o"></i></button><button type="button" title="CSV"><i class="fa fa-file-text-o"></i></button><button type="button" title="PDF"><i class="fa fa-file-pdf-o"></i></button><button type="button" title="Print" onclick="window.print()"><i class="fa fa-print"></i></button><button type="button" title="Columns"><i class="fa fa-columns"></i></button></div>';table.parentElement.insertBefore(toolbar,table);table.querySelectorAll('.action.view').forEach(x=>x.innerHTML='<i class="fa fa-eye"></i>');table.querySelectorAll('.action.edit').forEach(x=>x.innerHTML='<i class="fa fa-pencil"></i>');table.querySelectorAll('.action.delete').forEach(x=>x.innerHTML='<i class="fa fa-times"></i>');document.getElementById('recruitment_order_search').addEventListener('input',function(){const term=this.value.toLowerCase().trim();table.querySelectorAll('tbody tr').forEach(row=>row.style.display=row.textContent.toLowerCase().includes(term)?'':'none')})});
</script>
@endpush
@endsection
