@extends('admin.layouts.app')
@section('title', 'Written Test')
@section('content')
@push('styles')
<style>
.written-test-toolbar{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:8px 12px;border-bottom:1px solid #d8dce5}.written-test-search{width:220px;height:32px;border:1px solid #aeb8c6;border-radius:6px;padding:0 8px;font-size:12px;outline:0}.written-test-tools{display:flex;gap:4px}.written-test-tools button{width:30px;height:30px;border:0;border-radius:6px;background:#62676d;color:#fff;font-size:13px}.written-test-table{width:100%;table-layout:fixed;border-collapse:collapse}.written-test-table th{background:#626262!important;color:#fff!important;border:1px solid #858585;padding:8px 9px;font-size:11px;line-height:14px}.written-test-table td{border:1px solid #bfc8d4;padding:6px 8px;font-size:11px;line-height:15px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.written-test-table th:nth-child(1),.written-test-table td:nth-child(1){width:8%}.written-test-table th:nth-child(2),.written-test-table td:nth-child(2){width:23%}.written-test-table th:nth-child(3),.written-test-table td:nth-child(3){width:22%}.written-test-table th:nth-child(4),.written-test-table td:nth-child(4){width:18%}.written-test-table th:nth-child(5),.written-test-table td:nth-child(5){width:15%}.written-test-table th:nth-child(6),.written-test-table td:nth-child(6){width:14%}.written-test-table .marks-input,.written-test-table .total-input{width:75px!important;height:25px;padding:3px 5px;font-size:11px}.written-test-count{padding-top:8px;font-size:10px;color:#344054}@media(max-width:700px){.written-test-toolbar{align-items:flex-start;flex-direction:column}.written-test-search{width:100%}.written-test-tools{align-self:flex-end}}
</style>
@endpush
<section class="overflow-hidden rounded-md border border-[#d8dce5] bg-white shadow-sm"><div class="border-b border-[#d8dce5] px-4 py-3"><h2 class="text-[16px] font-medium">Written Test - Approved Candidates</h2></div><div class="p-3"><div id="message-container"></div><div class="overflow-x-auto"><table class="min-w-full border border-[#ccd5e3] text-left text-[12px]"><thead class="bg-[#626262] text-white"><tr><th class="px-2 py-2">ID</th><th class="px-2 py-2">Name</th><th class="px-2 py-2">Position</th><th class="px-2 py-2">CNIC</th><th class="px-2 py-2">Test Marks</th><th class="px-2 py-2">Total Marks</th></tr></thead><tbody>@forelse($candidates as $candidate)<tr class="border-t border-[#d8dce5]"><td class="px-2 py-2">{{$loop->iteration}}</td><td class="px-2 py-2">{{$candidate->full_name}}</td><td class="px-2 py-2">{{$candidate->position_applied}}</td><td class="px-2 py-2">{{$candidate->cnic}}</td><td class="px-2 py-2"><input type="number" min="0" class="marks-input input" data-id="{{$candidate->id}}" value="{{$candidate->written_test_marks ?? 0}}" placeholder="Marks"></td><td class="px-2 py-2"><input type="number" min="1" class="total-input input" data-id="{{$candidate->id}}" value="{{$candidate->written_test_total ?? 100}}" placeholder="Total"></td></tr>@empty<tr><td colspan="6" class="px-2 py-4 text-center">No approved candidates found</td></tr>@endforelse</tbody></table></div></div></section>
@push('styles')<style>.input{width:80px;border:1px solid #cfd6e0;padding:5px 7px;font-size:12px}.written-message{position:fixed;top:20px;right:20px;z-index:9999;min-width:280px;padding:10px 14px;border-radius:3px;color:#fff}.written-success{background:#198754}.written-error{background:#dc3545}</style>@endpush
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{let timer;const toast=(message,ok)=>{const el=document.createElement('div');el.className='written-message '+(ok?'written-success':'written-error');el.textContent=message;document.body.appendChild(el);setTimeout(()=>el.remove(),3000)};document.querySelectorAll('.marks-input,.total-input').forEach(input=>input.addEventListener('input',()=>{clearTimeout(timer);const id=input.dataset.id;timer=setTimeout(()=>{const marks=document.querySelector('.marks-input[data-id="'+id+'"]').value||0,total=document.querySelector('.total-input[data-id="'+id+'"]').value||100;fetch(@json(url('/admin/hrms/Writtentest')).replace(/\/$/,'')+'/'+id+'/update-marks',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content,'Accept':'application/json'},body:JSON.stringify({marks,total})}).then(async r=>({ok:r.ok,data:await r.json()})).then(({ok,data})=>toast(ok&&data.success?'Marks updated successfully!':(data.message||'Failed to update marks'),ok&&data.success)).catch(()=>toast('Error updating marks',false))},1000)}))})</script>@endpush
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',function(){const section=document.querySelector('section'),table=section?.querySelector('table');if(!section||!table)return;table.id='written_test_table';table.classList.add('written-test-table');const toolbar=document.createElement('div');toolbar.className='written-test-toolbar';toolbar.innerHTML='<input id="written_test_search" type="search" placeholder="Search..." class="written-test-search"><div class="written-test-tools"><button type="button" title="Copy"><i class="fa fa-copy"></i></button><button type="button" title="Excel"><i class="fa fa-file-excel-o"></i></button><button type="button" title="CSV"><i class="fa fa-file-text-o"></i></button><button type="button" title="PDF"><i class="fa fa-file-pdf-o"></i></button><button type="button" title="Print" onclick="window.print()"><i class="fa fa-print"></i></button><button type="button" title="Columns"><i class="fa fa-columns"></i></button></div>';table.parentElement.parentElement.insertBefore(toolbar,table.parentElement);document.getElementById('written_test_search').addEventListener('input',function(){const term=this.value.toLowerCase().trim();table.querySelectorAll('tbody tr').forEach(row=>row.style.display=row.textContent.toLowerCase().includes(term)?'':'none')})});
</script>
@endpush
@endsection
