@extends('admin.layouts.app')
@section('title', $viewMode ? 'View Job Advertisement' : ($advertisement ? 'Edit Job Advertisement' : 'Job Advertisements'))
@php
    $editing = $advertisement && !$viewMode;
    $v = fn($key, $fallback = '') => old($key, $advertisement?->{$key} ?? $fallback);
    $deadline = $advertisement?->deadline?->format('Y-m-d') ?? old('deadline', '');
@endphp
@section('content')
<div class="job-ad-layout items-start gap-3">
<section class="overflow-hidden rounded-md border border-[#d8dce5] bg-white shadow-sm"><div class="border-b border-[#d8dce5] px-4 py-3"><h2 class="text-[16px] font-medium">{{ $viewMode ? 'View Job Advertisement' : ($editing ? 'Edit Job Advertisement' : 'Add Job Advertisement') }}</h2></div>
<form method="POST" action="{{ $editing ? route('admin.hrms.jobadvertisements.update',$advertisement->id,false) : route('admin.hrms.jobadvertisements.store',absolute:false) }}" class="px-4 py-3">@csrf @if($editing) @method('PUT') @endif
@if(session('success'))<div class="notice success">{{ session('success') }}</div>@endif @if($errors->any())<div class="notice errorbox">Please correct the highlighted fields.</div>@endif
<div class="mb-3"><label class="label">Job Title <span>*</span></label>@if($viewMode)<input class="input" readonly value="{{ $v('job_title') }}">@else<select name="job_title" id="job_title" class="input" required><option value="">Select Position</option>@foreach($positions as $position)<option value="{{ $position }}" @selected($v('job_title')===$position)>{{ $position }}</option>@endforeach</select>@endif</div>
<div class="mb-3"><label class="label">Job Category <span>*</span></label>@if($viewMode)<input class="input" readonly value="{{ $v('category') }}">@else<select name="category" class="input" required><option value="">Select Category</option>@foreach($categories as $category)<option value="{{ $category->name }}" @selected($v('category')===$category->name)>{{ $category->name }}</option>@endforeach</select>@endif</div>
<div class="mb-3"><label class="label">Job Location <span>*</span></label>@if($viewMode)<input class="input" readonly value="{{ $v('location') }}">@else<select name="location" class="input" required><option value="">Select Campus</option>@foreach($campuses as $campus)<option value="{{ $campus->name }}" @selected($v('location')===$campus->name)>{{ $campus->name }}</option>@endforeach</select>@endif</div>
<div class="mb-3"><label class="label">Employment Type <span>*</span></label>@if($viewMode)<input class="input" readonly value="{{ $v('type') }}">@else<select name="type" id="type" class="input" required><option value="">Select Type</option>@foreach($types as $type)<option value="{{ $type }}" @selected($v('type')===$type)>{{ $type }}</option>@endforeach</select>@endif</div>
<div class="mb-3"><label class="label">Salary Range</label><input type="text" name="salary" id="salary" value="{{ $v('salary') }}" class="input" {{ $viewMode?'readonly':'' }}></div>
<div class="mb-3"><label class="label">Job Description <span>*</span></label><textarea name="description" class="input" rows="4" {{ $viewMode?'readonly':'required' }}>{{ $v('description') }}</textarea></div>
<div class="mb-3"><label class="label">Job Requirements <span>*</span></label><textarea name="requirements" class="input" rows="3" {{ $viewMode?'readonly':'required' }}>{{ $v('requirements') }}</textarea></div>
<div class="mb-3"><label class="label">Contact Email <span>*</span></label><input type="email" name="contact_email" value="{{ $v('contact_email') }}" class="input" {{ $viewMode?'readonly':'required' }}></div>
<div class="mb-3"><label class="label">Contact Phone</label><input type="text" name="contact_phone" value="{{ $v('contact_phone') }}" class="input" {{ $viewMode?'readonly':'' }}></div>
<div class="mb-3"><label class="label">Application Deadline <span>*</span></label><input type="date" name="deadline" value="{{ $deadline }}" class="input" {{ $viewMode?'readonly':'required' }}></div>
@if(!$viewMode)<div class="flex justify-end gap-2 pt-2"><a class="button secondary" href="{{ route('admin.hrms.jobadvertisements.index',absolute:false) }}">{{ $editing?'Cancel':'Reset' }}</a><button class="button primary">{{ $editing?'Update':'Save' }}</button></div>@else<div class="flex justify-end gap-2 pt-2"><a class="button secondary" href="{{ route('admin.hrms.jobadvertisements.index',absolute:false) }}">Back to List</a><a class="button primary" href="{{ route('admin.hrms.jobadvertisements.edit',$advertisement->id,false) }}">Edit</a></div>@endif
</form></section>
<section class="job-ad-records overflow-hidden rounded-md border border-[#d8dce5] bg-white shadow-sm"><div class="border-b border-[#d8dce5] px-4 py-3"><h2 class="text-[16px] font-medium">Job Advertisements List</h2></div><div class="job-ad-toolbar"><input id="job_ad_search" type="search" placeholder="Search..." class="job-ad-search"><div class="job-ad-tools"><button type="button" title="Copy"><i class="fa fa-copy"></i></button><button type="button" title="Excel"><i class="fa fa-file-excel-o"></i></button><button type="button" title="CSV"><i class="fa fa-file-text-o"></i></button><button type="button" title="PDF"><i class="fa fa-file-pdf-o"></i></button><button type="button" title="Print" onclick="window.print()"><i class="fa fa-print"></i></button><button type="button" title="Columns"><i class="fa fa-columns"></i></button></div></div><div class="overflow-x-auto p-3"><table id="job_ad_table" class="job-ad-table min-w-full border-collapse text-left text-[11px]"><thead><tr><th>ID <i class="fa fa-caret-down"></i></th><th>Job Title <i class="fa fa-caret-down"></i></th><th>Category <i class="fa fa-caret-down"></i></th><th>Location <i class="fa fa-caret-down"></i></th><th>Type <i class="fa fa-caret-down"></i></th><th>Deadline <i class="fa fa-caret-down"></i></th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($advertisements as $item)<tr class="job-ad-row"><td>{{ $loop->count - $loop->iteration + 1 }}</td><td>{{ $item->job_title }}</td><td>{{ $item->category }}</td><td>{{ $item->location }}</td><td>{{ $item->type }}</td><td>{{ $item->deadline?->format('Y-m-d') }}</td><td><select class="status-select input" data-id="{{ $item->id }}"><option value="active" @selected($item->status==='active')>Active</option><option value="inactive" @selected($item->status==='inactive')>Inactive</option></select></td><td class="job-ad-action"><a class="action view" title="View" href="{{ route('admin.hrms.jobadvertisements.show',$item->id,false) }}"><i class="fa fa-eye"></i></a><a class="action print" title="Print" href="{{ route('admin.hrms.jobadvertisements.print',$item->id,false) }}" target="_blank"><i class="fa fa-print"></i></a><a class="action edit" title="Edit" href="{{ route('admin.hrms.jobadvertisements.edit',$item->id,false) }}"><i class="fa fa-pencil"></i></a><form class="inline" method="POST" action="{{ route('admin.hrms.jobadvertisements.destroy',$item->id,false) }}" onsubmit="return confirm('Are you sure you want to delete this job advertisement?')">@csrf @method('DELETE')<button class="action delete" title="Delete"><i class="fa fa-times"></i></button></form></td></tr>@empty<tr><td colspan="8">No job advertisements found</td></tr>@endforelse</tbody></table><div class="job-ad-count">Records: {{ $advertisements->count() ? 1 : 0 }} to {{ $advertisements->count() }} of {{ $advertisements->count() }}</div></div></section>
</div>
@push('styles')
<style>
.job-ad-layout{display:grid;grid-template-columns:minmax(360px,1fr) minmax(0,2fr);align-items:start;gap:12px}.job-ad-toolbar{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:8px 12px;border-bottom:1px solid #d8dce5}.job-ad-search{width:220px;height:32px;border:1px solid #aeb8c6;border-radius:6px;padding:0 8px;font-size:12px;outline:0}.job-ad-tools{display:flex;gap:4px}.job-ad-tools button{width:30px;height:30px;border:0;border-radius:6px;background:#62676d;color:#fff;font-size:13px}.job-ad-table{width:100%;table-layout:fixed}.job-ad-table th{background:#626262!important;color:#fff!important;border:1px solid #858585;padding:7px 8px;font-size:11px;line-height:14px}.job-ad-table td{border:1px solid #bfc8d4;padding:5px 7px;font-size:11px;line-height:15px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.job-ad-table th:nth-child(1),.job-ad-table td:nth-child(1){width:6%}.job-ad-table th:nth-child(2),.job-ad-table td:nth-child(2){width:18%}.job-ad-table th:nth-child(3),.job-ad-table td:nth-child(3){width:15%}.job-ad-table th:nth-child(4),.job-ad-table td:nth-child(4){width:15%}.job-ad-table th:nth-child(5),.job-ad-table td:nth-child(5){width:11%}.job-ad-table th:nth-child(6),.job-ad-table td:nth-child(6){width:13%}.job-ad-table th:nth-child(7),.job-ad-table td:nth-child(7){width:10%}.job-ad-table th:nth-child(8),.job-ad-table td:nth-child(8){width:12%}.job-ad-table .job-ad-action{overflow:visible;text-overflow:clip}.job-ad-records .action{display:inline-flex;width:22px!important;height:22px!important;min-width:22px!important;align-items:center;justify-content:center;padding:0!important;margin:0 2px 0 0;border:0;font-size:10px;color:#fff}.job-ad-records .action.view{background:#17a2b8}.job-ad-records .action.print{background:#198754}.job-ad-records .action.edit{background:#264796}.job-ad-records .action.delete{background:#dc3545}.job-ad-count{padding-top:8px;font-size:10px;color:#344054}@media(max-width:900px){.job-ad-layout{grid-template-columns:1fr}.job-ad-toolbar{align-items:flex-start;flex-direction:column}.job-ad-search{width:100%}.job-ad-tools{align-self:flex-end}}
</style>
@endpush
@push('styles')<style>.label{display:block;margin-bottom:5px;font-size:13px;font-weight:600;color:#222}.label span{color:#e11d48}.input{width:100%;border:1px solid #cfd6e0;padding:7px 10px;font-size:13px;color:#333;outline:0}.input:focus{border-color:#264796}.notice{margin-bottom:12px;padding:8px 10px;font-size:12px}.success{border:1px solid #bbf7d0;background:#f0fdf4;color:#15803d}.errorbox{border:1px solid #fecaca;background:#fef2f2;color:#b91c1c}.button{display:inline-block;padding:7px 14px;font-size:12px;font-weight:600}.button.primary{border:0;background:#264796;color:#fff}.button.secondary{border:1px solid #cfd6e0;color:#333}.action{display:inline-flex;width:24px;height:24px;align-items:center;justify-content:center;margin-right:3px;color:#fff;font-weight:bold;text-decoration:none}.action.view{background:#17a2b8}.action.print{background:#198754}.action.edit{background:#264796}.action.delete{border:0;background:#dc3545;cursor:pointer}.status-select{width:100px;padding:4px 5px}</style>@endpush
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const title=document.getElementById('job_title'),salary=document.getElementById('salary'),type=document.getElementById('type');if(title)title.addEventListener('change',()=>{if(!title.value)return;fetch(@json(route('admin.hrms.jobadvertisements.salary-range',absolute:false)),{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content,'Accept':'application/json'},body:JSON.stringify({position:title.value})}).then(r=>r.json()).then(d=>{salary.value=d.salary||'';if(d.employment_type)type.value=d.employment_type})});document.querySelectorAll('.status-select').forEach(select=>select.addEventListener('change',()=>{const old=select.dataset.old||select.value;fetch(@json(url('/admin/hrms/jobadvertisements')).replace(/\/$/,'')+'/'+select.dataset.id+'/status',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content,'Accept':'application/json'},body:JSON.stringify({status:select.value})}).then(r=>r.json()).then(d=>{if(!d.success)select.value=old;else select.dataset.old=select.value}).catch(()=>select.value=old)}))})</script>@endpush
@push('scripts')
<script>document.addEventListener('DOMContentLoaded',function(){const search=document.getElementById('job_ad_search');if(!search)return;search.addEventListener('input',function(){const term=this.value.toLowerCase().trim();document.querySelectorAll('#job_ad_table .job-ad-row').forEach(function(row){row.style.display=row.textContent.toLowerCase().includes(term)?'':'none'})})});</script>
@endpush
@endsection
