@extends('admin.layouts.app')
@section('title', $viewMode ? 'View Job Offer Letter' : ($offer ? 'Edit Job Offer Letter' : 'Job Offer Letters'))
@php $editing=$offer&&!$viewMode; $v=fn($key,$fallback='')=>old($key,$offer?->{$key}??$fallback); $offerDate=$offer?->offer_date?->format('Y-m-d')??old('offer_date',$today); $joiningDate=$offer?->joining_date?->format('Y-m-d')??old('joining_date',''); @endphp
@section('content')
@push('styles')
<style>
.grid.gap-3{display:grid;grid-template-columns:minmax(360px,1fr) minmax(0,2fr);align-items:start;gap:12px}.grid.gap-3>section:last-child{min-width:0}.job-offer-toolbar{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:8px 12px;border-bottom:1px solid #d8dce5}.job-offer-search{width:220px;height:32px;border:1px solid #aeb8c6;border-radius:6px;padding:0 8px;font-size:12px;outline:0}.job-offer-tools{display:flex;gap:4px}.job-offer-tools button{width:30px;height:30px;border:0;border-radius:6px;background:#62676d;color:#fff;font-size:13px}.job-offer-table{width:100%;table-layout:fixed;border-collapse:collapse}.job-offer-table th{background:#626262!important;color:#fff!important;border:1px solid #858585;padding:7px 8px;font-size:11px;line-height:14px}.job-offer-table td{border:1px solid #bfc8d4;padding:5px 7px;font-size:11px;line-height:15px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.job-offer-table th:nth-child(1),.job-offer-table td:nth-child(1){width:14%}.job-offer-table th:nth-child(2),.job-offer-table td:nth-child(2){width:20%}.job-offer-table th:nth-child(3),.job-offer-table td:nth-child(3){width:15%}.job-offer-table th:nth-child(4),.job-offer-table td:nth-child(4){width:15%}.job-offer-table th:nth-child(5),.job-offer-table td:nth-child(5){width:12%}.job-offer-table th:nth-child(6),.job-offer-table td:nth-child(6){width:12%}.job-offer-table th:nth-child(7),.job-offer-table td:nth-child(7){width:10%}.job-offer-table th:nth-child(8),.job-offer-table td:nth-child(8){width:12%}.job-offer-table td:last-child{overflow:visible;text-overflow:clip}.job-offer-records .action{display:inline-flex;width:22px!important;height:22px!important;min-width:22px!important;align-items:center;justify-content:center;padding:0!important;margin:0 2px 0 0;border:0;font-size:10px;color:#fff}.job-offer-records .action.view{background:#17a2b8}.job-offer-records .action.print{background:#198754}.job-offer-records .action.edit{background:#264796}.job-offer-records .action.delete{background:#dc3545}.job-offer-count{padding-top:8px;font-size:10px;color:#344054}@media(max-width:900px){.grid.gap-3{grid-template-columns:1fr}.job-offer-toolbar{align-items:flex-start;flex-direction:column}.job-offer-search{width:100%}.job-offer-tools{align-self:flex-end}}
</style>
@endpush
<div class="grid gap-3 xl:grid-cols-[minmax(320px,1fr)_minmax(520px,2fr)]"><section class="overflow-hidden rounded-md border border-[#d8dce5] bg-white shadow-sm"><div class="border-b border-[#d8dce5] px-4 py-3"><h2 class="text-[16px] font-medium">{{ $viewMode?'View Job Offer Letter':($editing?'Edit Job Offer Letter':'Add Job Offer Letter') }}</h2></div><form method="POST" action="{{ $editing?route('admin.hrms.joboffers.update',$offer->id,false):route('admin.hrms.joboffers.store',absolute:false) }}" class="px-4 py-3">@csrf @if($editing) @method('PUT') @endif @if(session('success'))<div class="notice success">{{session('success')}}</div>@endif @if($errors->any())<div class="notice errorbox">Please correct the highlighted fields.</div>@endif
<div class="mb-3"><label class="label">Reference No</label><input class="input" readonly value="{{$offer->reference_no??'Auto Generated'}}"></div>
<div class="mb-3"><label class="label">Candidate Name <span>*</span></label>@if($viewMode)<input class="input" readonly value="{{$v('candidate_name')}}">@else<select name="candidate_name" id="candidate_name" class="input" required><option value="">Select Candidate</option>@foreach($candidates as $candidate)<option value="{{$candidate->full_name}}" data-position="{{$candidate->position_applied}}" @selected($v('candidate_name')===$candidate->full_name)>{{$candidate->full_name}} - {{$candidate->position_applied}}</option>@endforeach</select>@endif</div>
@foreach([['position','Position',true],['department','Department',true]] as [$name,$label,$required])<div class="mb-3"><label class="label">{{$label}} <span>*</span></label><input type="text" name="{{$name}}" value="{{$v($name)}}" class="input" {{ $viewMode?'readonly':($required?'required':'') }}></div>@endforeach
<div class="mb-3"><label class="label">Offer Date <span>*</span></label><input type="date" name="offer_date" value="{{$offerDate}}" class="input" {{ $viewMode?'readonly':'required' }}></div><div class="mb-3"><label class="label">Joining Date <span>*</span></label><input type="date" name="joining_date" value="{{$joiningDate}}" class="input" {{ $viewMode?'readonly':'required' }}></div><div class="mb-3"><label class="label">Basic Salary (per month) <span>*</span></label><input type="number" name="salary" value="{{$v('basic_salary')}}" min="0" step="0.01" class="input" {{ $viewMode?'readonly':'required' }}></div>
@if($viewMode)<div class="mb-3"><label class="label">Status</label><input class="input" readonly value="{{ucfirst($offer->status??'pending')}}"></div>@elseif($editing)<div class="mb-3"><label class="label">Status</label><select name="status" class="input">@foreach($statuses as $status)<option value="{{$status}}" @selected($offer->status===$status)>{{ucfirst($status)}}</option>@endforeach</select></div>@endif
@if(!$viewMode)<div class="flex justify-end gap-2 pt-2"><a class="button secondary" href="{{route('admin.hrms.joboffers.index',absolute:false)}}">{{$editing?'Cancel':'Reset'}}</a><button class="button primary">{{$editing?'Update':'Save'}}</button></div>@else<div class="flex justify-end gap-2 pt-2"><a class="button secondary" href="{{route('admin.hrms.joboffers.index',absolute:false)}}">Back to List</a><a class="button primary" href="{{route('admin.hrms.joboffers.edit',$offer->id,false)}}">Edit</a></div>@endif</form></section>
<section class="overflow-hidden rounded-md border border-[#d8dce5] bg-white shadow-sm"><div class="border-b border-[#d8dce5] px-4 py-3"><h2 class="text-[16px] font-medium">Job Offer Letters List</h2></div><div class="overflow-x-auto p-3"><table class="min-w-full border border-[#ccd5e3] text-left text-[12px]"><thead class="bg-[#626262] text-white"><tr><th class="px-2 py-2">Ref No</th><th class="px-2 py-2">Candidate Name</th><th class="px-2 py-2">Position</th><th class="px-2 py-2">Department</th><th class="px-2 py-2">Offer Date</th><th class="px-2 py-2">Joining Date</th><th class="px-2 py-2">Salary</th><th class="px-2 py-2">Action</th></tr></thead><tbody>@forelse($offers as $item)<tr class="border-t border-[#d8dce5]"><td class="px-2 py-2">{{$item->reference_no??$item->id}}</td><td class="px-2 py-2"><strong>{{$item->candidate_name}}</strong></td><td class="px-2 py-2">{{$item->position}}</td><td class="px-2 py-2">{{$item->department}}</td><td class="px-2 py-2">{{$item->offer_date?->format('Y-m-d')}}</td><td class="px-2 py-2">{{$item->joining_date?->format('Y-m-d')}}</td><td class="px-2 py-2">{{number_format((float)$item->basic_salary,2)}}</td><td class="whitespace-nowrap px-2 py-2"><a class="action view" href="{{route('admin.hrms.joboffers.show',$item->id,false)}}">●</a><a class="action print" target="_blank" href="{{route('admin.hrms.joboffers.print',$item->id,false)}}">▣</a><a class="action edit" href="{{route('admin.hrms.joboffers.edit',$item->id,false)}}">✎</a><form class="inline" method="POST" action="{{route('admin.hrms.joboffers.destroy',$item->id,false)}}" onsubmit="return confirm('Are you sure you want to delete this offer letter?')">@csrf @method('DELETE')<button class="action delete">×</button></form></td></tr>@empty<tr><td colspan="8" class="px-2 py-4 text-center">No job offer letters found</td></tr>@endforelse</tbody></table></div></section></div>
@push('styles')<style>.label{display:block;margin-bottom:5px;font-size:13px;font-weight:600;color:#222}.label span{color:#e11d48}.input{width:100%;border:1px solid #cfd6e0;padding:7px 10px;font-size:13px;color:#333;outline:0}.notice{margin-bottom:12px;padding:8px;font-size:12px}.success{background:#f0fdf4;color:#15803d}.errorbox{background:#fef2f2;color:#b91c1c}.button{display:inline-block;padding:7px 14px;font-size:12px;font-weight:600}.primary{background:#264796;color:#fff}.secondary{border:1px solid #cfd6e0;color:#333}.action{display:inline-flex;width:24px;height:24px;align-items:center;justify-content:center;margin-right:3px;color:#fff;text-decoration:none;border:0}.view{background:#17a2b8}.print{background:#198754}.edit{background:#264796}.delete{background:#dc3545;cursor:pointer}</style>@endpush
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const c=document.getElementById('candidate_name');if(c)c.addEventListener('change',()=>{const o=c.options[c.selectedIndex],p=document.querySelector('[name=position]');if(o.dataset.position)p.value=o.dataset.position})})</script>@endpush
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',function(){const records=document.querySelector('.grid.gap-3>section:last-child'),table=records?.querySelector('table');if(!records||!table)return;records.classList.add('job-offer-records');table.id='job_offer_table';table.classList.add('job-offer-table');const toolbar=document.createElement('div');toolbar.className='job-offer-toolbar';toolbar.innerHTML='<input id="job_offer_search" type="search" placeholder="Search..." class="job-offer-search"><div class="job-offer-tools"><button type="button" title="Copy"><i class="fa fa-copy"></i></button><button type="button" title="Excel"><i class="fa fa-file-excel-o"></i></button><button type="button" title="CSV"><i class="fa fa-file-text-o"></i></button><button type="button" title="PDF"><i class="fa fa-file-pdf-o"></i></button><button type="button" title="Print" onclick="window.print()"><i class="fa fa-print"></i></button><button type="button" title="Columns"><i class="fa fa-columns"></i></button></div>';table.parentElement.insertBefore(toolbar,table);table.querySelectorAll('.action.view').forEach(x=>x.innerHTML='<i class="fa fa-eye"></i>');table.querySelectorAll('.action.print').forEach(x=>x.innerHTML='<i class="fa fa-print"></i>');table.querySelectorAll('.action.edit').forEach(x=>x.innerHTML='<i class="fa fa-pencil"></i>');table.querySelectorAll('.action.delete').forEach(x=>x.innerHTML='<i class="fa fa-times"></i>');document.getElementById('job_offer_search').addEventListener('input',function(){const term=this.value.toLowerCase().trim();table.querySelectorAll('tbody tr').forEach(row=>row.style.display=row.textContent.toLowerCase().includes(term)?'':'none')})});
</script>
@endpush
@endsection
