@extends('admin.layouts.app')
@section('title', 'Merit List')
@section('content')
<section class="overflow-hidden rounded-md border border-[#d8dce5] bg-white shadow-sm"><div class="border-b border-[#d8dce5] px-4 py-3"><h2 class="text-[16px] font-medium">Merit List - Final Rankings</h2></div><div class="p-3"><div class="overflow-x-auto"><table class="min-w-full border border-[#ccd5e3] text-left text-[12px]"><thead class="bg-[#626262] text-white"><tr><th class="px-2 py-2">Rank</th><th class="px-2 py-2">Name</th><th class="px-2 py-2">Position</th><th class="px-2 py-2">Written Test</th><th class="px-2 py-2">Interview Score</th><th class="px-2 py-2">Total Score</th><th class="px-2 py-2">Percentage</th></tr></thead><tbody>@forelse($candidates as $candidate) @php $written=(int)($candidate->written_test_marks??0);$writtenTotal=(int)($candidate->written_test_total??100);$interview=(int)($candidate->interview_marks??0);$writtenPercentage=$writtenTotal>0?round(($written/$writtenTotal)*100,2):0;$interviewPercentage=round(($interview/100)*100,2);$possible=$writtenTotal+100;$percentage=$possible>0?round((($written+$interview)/$possible)*100,2):0; @endphp<tr class="border-t border-[#d8dce5]"><td class="px-2 py-2"><strong>{{$loop->iteration}}</strong>@if($loop->iteration===1)<span class="medal gold">★</span>@elseif($loop->iteration===2)<span class="medal silver">●</span>@elseif($loop->iteration===3)<span class="medal bronze">●</span>@endif</td><td class="px-2 py-2"><strong>{{$candidate->full_name}}</strong></td><td class="px-2 py-2">{{$candidate->position_applied}}</td><td class="px-2 py-2">{{$written}}/{{$writtenTotal}} <small>({{$writtenPercentage}}%)</small></td><td class="px-2 py-2">{{$interview}}/100 <small>({{$interviewPercentage}}%)</small></td><td class="px-2 py-2"><strong>{{$written+$interview}}</strong></td><td class="px-2 py-2"><span class="badge {{ $percentage>=80?'good':($percentage>=60?'warn':'plain') }}">{{$percentage}}%</span></td></tr>@empty<tr><td colspan="7" class="px-2 py-4 text-center">No candidates found in merit list</td></tr>@endforelse</tbody></table></div></div></section>
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',function(){const section=document.querySelector('section'),table=section?.querySelector('table');if(!section||!table)return;table.id='merit_table';table.classList.add('merit-table');const toolbar=document.createElement('div');toolbar.className='merit-toolbar';toolbar.innerHTML='<input id="merit_search" type="search" placeholder="Search..." class="merit-search"><div class="merit-tools"><button type="button" title="Copy"><i class="fa fa-copy"></i></button><button type="button" title="Excel"><i class="fa fa-file-excel-o"></i></button><button type="button" title="CSV"><i class="fa fa-file-text-o"></i></button><button type="button" title="PDF"><i class="fa fa-file-pdf-o"></i></button><button type="button" title="Print" onclick="window.print()"><i class="fa fa-print"></i></button><button type="button" title="Columns"><i class="fa fa-columns"></i></button></div>';table.parentElement.parentElement.insertBefore(toolbar,table.parentElement);document.getElementById('merit_search').addEventListener('input',function(){const term=this.value.toLowerCase().trim();table.querySelectorAll('tbody tr').forEach(row=>row.style.display=row.textContent.toLowerCase().includes(term)?'':'none')})});
</script>
@endpush
@endsection
