@extends('admin.layouts.app')
@section('title', $viewMode ? 'View Interview Rating' : ($rating ? 'Edit Interview Rating' : 'Interview Ratings'))
@php $editing=$rating&&!$viewMode; $v=fn($key,$fallback='')=>old($key,$rating?->{$key}??$fallback); $date=$rating?->interview_date?->format('Y-m-d')??old('interview_date',$today); @endphp
@section('content')
<div class="grid gap-3 xl:grid-cols-[minmax(320px,1fr)_minmax(520px,2fr)]"><section class="overflow-hidden rounded-md border border-[#d8dce5] bg-white shadow-sm"><div class="border-b border-[#d8dce5] px-4 py-3"><h2 class="text-[16px] font-medium">{{ $viewMode?'View Interview Rating':($editing?'Edit Interview Rating':'Add Interview Rating') }}</h2></div><form method="POST" action="{{ $editing?route('admin.hrms.interviewratings.update',$rating->id,false):route('admin.hrms.interviewratings.store',absolute:false) }}" class="px-4 py-3">@csrf @if($editing) @method('PUT') @endif @if(session('success'))<div class="notice success">{{session('success')}}</div>@endif @if($errors->any())<div class="notice errorbox">Please correct the highlighted fields.</div>@endif
<div class="mb-3"><label class="label">Candidate Name <span>*</span></label>@if($viewMode)<input class="input" readonly value="{{$v('candidate_name')}}">@else<select name="candidate_name" id="candidate_name" class="input" required><option value="">Select Candidate</option>@foreach($candidates as $candidate)<option value="{{$candidate->full_name}}" data-position="{{$candidate->position_applied}}" data-salary="{{$candidate->min_salary_acceptable}}" @selected($v('candidate_name')===$candidate->full_name)>{{$candidate->full_name}}</option>@endforeach</select>@endif</div>
<div class="mb-3"><label class="label">Interview Date <span>*</span></label><input type="date" name="interview_date" value="{{$date}}" class="input" {{ $viewMode?'readonly':'required' }}></div>
<div class="mb-3"><label class="label">Position Applied <span>*</span></label><input type="text" name="position_applied" value="{{$v('position_applied')}}" class="input" {{ $viewMode?'readonly':'required' }}></div>
<div class="mb-3"><label class="label">Salary Expectation</label><input type="text" name="salary_expectation" value="{{$v('salary_expectation')}}" class="input" {{ $viewMode?'readonly':'' }}></div>
@foreach($ratingFields as $field) @php $labels=['appearance_rating'=>'Appearance Rating (1-10)','communication_rating'=>'Communication Rating (1-10)','reasoning_rating'=>'Reasoning Rating (1-10)','education_rating'=>'Education Rating (1-10)','job_knowledge_rating'=>'Job Knowledge Rating (1-10)','work_experience_rating'=>'Work Experience Rating (1-10)','general_knowledge_rating'=>'General Knowledge Rating (1-10)','iq_level_rating'=>'IQ Level Rating (1-10)','pose_maturity_rating'=>'Pose Maturity Rating (1-10)','personality_rating'=>'Personality Rating (1-10)']; @endphp<div class="mb-3"><label class="label">{{$labels[$field]}}</label><input type="number" min="0" max="10" name="{{$field}}" value="{{$v($field)}}" class="input" {{ $viewMode?'readonly':'' }}></div>@endforeach
<div class="mb-3"><label class="label">Final Decision</label>@if($viewMode)<input class="input" readonly value="{{$v('final_decision')}}">@else<select name="final_decision" class="input"><option value="pending" @selected($v('final_decision','pending')==='pending')>Pending</option><option value="recommended" @selected($v('final_decision')==='recommended')>Recommended</option><option value="not_recommended" @selected($v('final_decision')==='not_recommended')>Not Recommended</option></select>@endif</div>
@if(!$viewMode)<div class="flex justify-end gap-2 pt-2"><a class="button secondary" href="{{route('admin.hrms.interviewratings.index',absolute:false)}}">{{$editing?'Cancel':'Reset'}}</a><button class="button primary">{{$editing?'Update':'Save'}}</button></div>@else<div class="flex justify-end gap-2 pt-2"><a class="button secondary" href="{{route('admin.hrms.interviewratings.index',absolute:false)}}">Back to List</a><a class="button primary" href="{{route('admin.hrms.interviewratings.edit',$rating->id,false)}}">Edit</a></div>@endif</form></section>
<section class="overflow-hidden rounded-md border border-[#d8dce5] bg-white shadow-sm"><div class="border-b border-[#d8dce5] px-4 py-3"><h2 class="text-[16px] font-medium">Interview Ratings List</h2></div><div class="overflow-x-auto p-3"><table class="min-w-full border border-[#ccd5e3] text-left text-[12px]"><thead class="bg-[#626262] text-white"><tr><th class="px-2 py-2">ID</th><th class="px-2 py-2">Candidate</th><th class="px-2 py-2">Position</th><th class="px-2 py-2">Interview Date</th><th class="px-2 py-2">Total Points</th><th class="px-2 py-2">Decision</th><th class="px-2 py-2">Action</th></tr></thead><tbody>@forelse($ratings as $item)<tr class="border-t border-[#d8dce5]"><td class="px-2 py-2">{{$item->id}}</td><td class="px-2 py-2">{{$item->candidate_name}}</td><td class="px-2 py-2">{{$item->position_applied}}</td><td class="px-2 py-2">{{$item->interview_date?->format('Y-m-d')}}</td><td class="px-2 py-2">{{$item->total_points??0}}</td><td class="px-2 py-2"><select class="decision-select input" data-id="{{$item->id}}"><option value="pending" @selected($item->final_decision==='pending')>Pending</option><option value="recommended" @selected($item->final_decision==='recommended')>Recommended</option><option value="not_recommended" @selected($item->final_decision==='not_recommended')>Not Recommended</option></select></td><td class="whitespace-nowrap px-2 py-2"><a class="action view" href="{{route('admin.hrms.interviewratings.show',$item->id,false)}}">●</a><a class="action edit" href="{{route('admin.hrms.interviewratings.edit',$item->id,false)}}">✎</a><form class="inline" method="POST" action="{{route('admin.hrms.interviewratings.destroy',$item->id,false)}}" onsubmit="return confirm('Are you sure you want to delete this interview rating?')">@csrf @method('DELETE')<button class="action delete">×</button></form></td></tr>@empty<tr><td colspan="7" class="px-2 py-4 text-center">No interview ratings found</td></tr>@endforelse</tbody></table></div></section></div>
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const candidate=document.getElementById('candidate_name');if(candidate)candidate.addEventListener('change',()=>{const o=candidate.options[candidate.selectedIndex],p=document.querySelector('[name=position_applied]'),s=document.querySelector('[name=salary_expectation]');if(o.dataset.position)p.value=o.dataset.position;if(o.dataset.salary){const n=parseFloat(o.dataset.salary);s.value=Number.isNaN(n)?o.dataset.salary:'Rs. '+n.toFixed(0)+'.00'}});document.querySelectorAll('.decision-select').forEach(select=>select.addEventListener('change',()=>{const old=select.dataset.old||select.value;fetch(@json(url('/admin/hrms/interviewratings')).replace(/\/$/,'')+'/'+select.dataset.id+'/decision',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content,'Accept':'application/json'},body:JSON.stringify({decision:select.value})}).then(r=>r.json()).then(d=>{if(!d.success)select.value=old;else select.dataset.old=select.value}).catch(()=>select.value=old)}))})</script>@endpush
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',function(){
    const records=document.querySelector('.grid.gap-3>section:last-child'),table=records?.querySelector('table');
    if(!records||!table)return;
    records.classList.add('interview-rating-records');table.id='interview_rating_table';table.classList.add('interview-rating-table');
    const toolbar=document.createElement('div');toolbar.className='interview-rating-toolbar';toolbar.innerHTML='<input id="interview_rating_search" type="search" placeholder="Search..." class="interview-rating-search"><div class="interview-rating-tools"><button type="button" title="Copy"><i class="fa fa-copy"></i></button><button type="button" title="Excel"><i class="fa fa-file-excel-o"></i></button><button type="button" title="CSV"><i class="fa fa-file-text-o"></i></button><button type="button" title="PDF"><i class="fa fa-file-pdf-o"></i></button><button type="button" title="Print" onclick="window.print()"><i class="fa fa-print"></i></button><button type="button" title="Columns"><i class="fa fa-columns"></i></button></div>';table.parentElement.insertBefore(toolbar,table);
    table.querySelectorAll('.action.view').forEach(x=>x.innerHTML='<i class="fa fa-eye"></i>');table.querySelectorAll('.action.edit').forEach(x=>x.innerHTML='<i class="fa fa-pencil"></i>');table.querySelectorAll('.action.delete').forEach(x=>x.innerHTML='<i class="fa fa-times"></i>');
    document.getElementById('interview_rating_search').addEventListener('input',function(){const term=this.value.toLowerCase().trim();table.querySelectorAll('tbody tr').forEach(row=>row.style.display=row.textContent.toLowerCase().includes(term)?'':'none')});
});
</script>
@endpush
@endsection
